### ISSUE TITLE
Requests for `pro.juxt` and `pro.juxt.crux` group-ids

### ISSUE THREAD

**Issue by jarohen** [clojars/administration#100]
We are requesting verification of a new group. The group name is `pro.juxt`. Could we also verify `pro.juxt.crux` and `pro.juxt.crux-labs` as sub-groups?

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)

- [x] I have added a TXT DNS record for the domain that has a value of `clojars james-henderson`

Cheers!

James

cc @malcolmsparks, @jonpither, @refset, @hraberg

**Comment by jarohen** [comment]
Realise I can probably add the others once the group's been verified - feel free to just add me if that's easier :)

**Comment by tobias** [comment]
Hi @jarohen! 

I can verify both `pro.juxt` and `pro.juxt.crux` based on a TXT record on `juxt.pro`.Can you confirm the TXT records are set? I can't see them yet (though they may just not be fully propagated):

```
$ dig txt juxt.pro

; <<>> DiG 9.16.1-Ubuntu <<>> txt juxt.pro
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 217
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;juxt.pro.			IN	TXT

;; ANSWER SECTION:
juxt.pro.		1799	IN	CNAME	proxy-ssl.webflow.com.
proxy-ssl.webflow.com.	49	IN	CNAME	proxy-ssl-geo.webflow.com.

;; Query time: 83 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Jun 30 07:33:13 EDT 2021
;; MSG SIZE  rcvd: 100
```

Also, yes, I'll just add you, and you can add everyone else.

**Comment by jarohen** [comment]
Aha, looks like we have a CNAME on the root of the domain, so anything else I set on there is getting ignored...

Have pinged someone internally to take a look - will get back to you.

**Comment by jarohen** [comment]
Sorted, should be good now @tobias :crossed_fingers:

**Comment by tobias** [comment]
I can see it now, thanks @jarohen. However, the `pro.juxt` group already exists and you aren't a member, only @malcolmsparks is :(. Sorry to be pedantic about this, but can you either set the TXT record to Malcolm's Clojars username and I can verify the group under their name, or have them add you to the group in Clojars?

**Comment by jarohen** [comment]
Not at all, right to be pedantic :)

I've added another TXT record (looks like it has a 15 min TTL on though) and will go beg him for access!

**Comment by jarohen** [comment]
Ah, sorry to be a pain, could I also add `pro.juxt.crux-labs` as a group, when it comes around?

**Comment by tobias** [comment]
No pain at all!

All three groups (`pro.juxt`, `pro.juxt.crux`, `pro.juxt.crux-labs`) have been verified, and the latter two created with you as the sole member. 

You can delete the TXT records if you like.

**Comment by jarohen** [comment]
That's great @tobias, thanks for all your help today :pray:
