### ISSUE TITLE
group verification for com.widdindustries

### ISSUE THREAD

**Issue by henryw374** [clojars/administration#101]
I am requesting verification of an  existing group. The group name is: com.widdindustries

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars henryw374`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.widdindustries has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by henryw374** [comment]
thanks
