### ISSUE TITLE
Requesting verification for com.nomistech

### ISSUE THREAD

**Issue by simon-katz** [clojars/administration#102]
I am requesting verification of an existing group. The group name is: com.nomistech

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars nomiskatz `

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.nomistech has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
