### ISSUE TITLE
Requesting verification of edu.bard

### ISSUE THREAD

**Issue by hsartoris-bard** [clojars/administration#103]
I am requesting verification of an existing group. The group name is: edu.bard

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

As this is a group representing an organization, I would like to avoid a verification method explicitly tied to my Github username, if at all possible; please let me know if there's alternative, such as basing membership/ownership on our Github organization (https://github.com/bardcollege).

Thank you!

**Comment by danielcompton** [comment]
Hi @hsartoris-bard, you can verify edu.bard by creating a TXT DNS record for the bard.edu domain with the value `clojars hsartoris-bard` - https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-do-i-verify-a-group-name.

**Comment by tobias** [comment]
Hi @hsartoris-bard - also note that the TXT record is temporary; it can be deleted once we verify the domain if that helps.

**Comment by hsartoris-bard** [comment]
@tobias That works - record has been added, thanks!

**Comment by tobias** [comment]
Great!

The group https://clojars.org/groups/edu.bard has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by hsartoris-bard** [comment]
Thanks again
