### ISSUE TITLE
to.fluent

### ISSUE THREAD

**Issue by eneroth** [clojars/administration#104]
I am requesting verification of a [new | existing] group. The group name is: to.fluent

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars fluent`

**Comment by tobias** [comment]
The group https://clojars.org/groups/to.fluent has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
