### ISSUE TITLE
Requesting groups (io|com).github.clojure-lsp

### ISSUE THREAD

**Issue by ericdallo** [clojars/administration#105]
I am requesting verification of a new group. The group name is: com.github.clojure-lsp & io.github.clojure-lsp

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

I've created empty repo under the clojure-lsp github org: https://github.com/clojure-lsp/clojars_ericdallo

**Comment by tobias** [comment]
The groups https://clojars.org/groups/com.github.clojure-lsp and https://clojars.org/groups/io.github.clojure-lsp have been verified and you should now see the "verified" badge when you view them on Clojars. You can delete the verification repo if you like.
