### ISSUE TITLE
create a "tolitius" group

### ISSUE THREAD

**Issue by tolitius** [clojars/administration#106]
I am requesting verification of a new group. The group name is: `com.tolitius` or `tolitius` (if possible)

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

```
$ dig txt tolitius.com

;; ANSWER SECTION:
tolitius.com.		1799	IN	TXT	"clojars tolitius"
```

one question I have is whether it is possible to still have it as `tolitius/foo` vs. `com.tolitius/foo`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.tolitius has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

Unfortunately we are only verifying  reverse-domain-based groups, so `tolitius` is not verifiable. You can continue to publish new versions of projects deployed under `tolitius`, but won't be able to create new projects under that group.

**Comment by tolitius** [comment]
great, thanks for all your work on clojars Toby!
