### ISSUE TITLE
Change my username from asciian to taniguchi

### ISSUE THREAD

**Issue by tani** [clojars/administration#109]
I changed my username from asciian. I want to use a new username taniguchi.
Is it possible to change my username?  Should I send some personal information such as the mail address I registered for?
Thank you for the great service.

**Comment by danielcompton** [comment]
Sorry for the delay, I'll get to this soon.

**Comment by danielcompton** [comment]
@tani you can create a new Clojars user with the username taniguchi. Would that work for you?

**Comment by tani** [comment]
That's a nice idea. Created it. Thank you for taking your time.

**Comment by tani** [comment]
Can I reconnect my GitHub account from asciian to taniguchi?

**Comment by tobias** [comment]
Hi @tani - you can log in as `asciian` and add the `taniguchi` user to the `com.github.tani` and `io.github.tani` groups as an admin. This will give your new user the same access to those groups that `asciian` has.

**Comment by tani** [comment]
Thanks！‘
