### ISSUE TITLE
Request to verifify com.acceleratedtext

### ISSUE THREAD

**Issue by zmedelis** [clojars/administration#11]
I am requesting verification of a [new | existing] group. The group name is: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars-11 zm`

**Comment by tobias** [comment]
Thanks! 

The group `com.acceleratedtext` has been verified. There isn't (yet) a way to see that on the site, but I hope to add that soon. You can delete the TXT record if you like.
