### ISSUE TITLE
New Group Creation for `com.eigenbahn`

### ISSUE THREAD

**Issue by p3r7** [clojars/administration#110]
I am requesting verification of a **new** group. The group name is: `com.eigenbahn`

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars eigen`

```
$ dig -t txt eigenbahn.com
; <<>> DiG 9.16.1-Ubuntu <<>> -t txt eigenbahn.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32401
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;eigenbahn.com.			IN	TXT

;; ANSWER SECTION:
eigenbahn.com.		300	IN	TXT	"clojars eigen"
[...]
```

Thanks in advance :bow:

**Comment by danielcompton** [comment]
Sorry for the delay, I'll get to this soon.

**Comment by danielcompton** [comment]
The group `com.eigenbahn` has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like. Thanks!
