### ISSUE TITLE
io.vouch group registration

### ISSUE THREAD

**Issue by swannodette** [clojars/administration#111]
I am requesting verification of a new group. The group name is: 

- [x] This group is [io.vouch](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars dnolen-vouch`

**Comment by danielcompton** [comment]
Sorry for the delay, I'll get to this soon.

**Comment by danielcompton** [comment]
The group `io.vouch` has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like. Thanks!

**Comment by swannodette** [comment]
Thank you!
