### ISSUE TITLE
New Group Creation: org.vuxu

### ISSUE THREAD

**Issue by leahneukirchen** [clojars/administration#112]
I am requesting verification of a new group. The group name is: org.vuxu

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain vuxu.org that has a value of `clojars leahneukirchen`

**Comment by danielcompton** [comment]
Sorry for the delay, I'll get to this soon.

**Comment by danielcompton** [comment]
The group `org.vuxu` has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like. Thanks!
