### ISSUE TITLE
Group verification: io.github.narracion

### ISSUE THREAD

**Issue by xsc** [clojars/administration#113]
I am requesting verification of a new group. The group name is: `io.github.narracion`

- [x] This is a Github organisation.
- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by danielcompton** [comment]
Sorry for the delay, I'll get to this soon.

**Comment by danielcompton** [comment]
@xsc this should be automatically verified when you login via GitHub?

**Comment by xsc** [comment]
Hm, I've logged in via Github, but it does not seem like it automatically creates/verifies groups for Github organisations. (Which is sensible, since otherwise someone that should not be able to deploy within an organisation could be allowed to do so, just by being quicker to log into Clojars than the actual organisation admins.)

**Comment by danielcompton** [comment]
Ah right, I missed this: https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-do-i-verify-a-group-name

Could you create a public repo for this at github.com/narracion/clojars-verification-yqbn ? I'll then verify it and you can delete the repo.

**Comment by tobias** [comment]
Just checking in @xsc - have you had a chance to create the verification repo?

**Comment by xsc** [comment]
@tobias Thanks for reaching out! I have now created the repository.

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.github.narracion has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the verification repo if you like.
