### ISSUE TITLE
New Group Creation: com.works-hub

### ISSUE THREAD

**Issue by acron0** [clojars/administration#114]
I am requesting verification of a new group. The group name is: com.works-hub

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars acron0`

**Comment by danielcompton** [comment]
Sorry for the delay, I'll get to this soon.

**Comment by danielcompton** [comment]
The group `com.works-hub` has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
