### ISSUE TITLE
Group verification for `com.jakemccrary`

### ISSUE THREAD

**Issue by jakemcc** [clojars/administration#115]
I am requesting verification of a existing group. The group name is: 

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars jakemcc`

The group is `com.jakemccrary`

```
$ dig -t txt jakemccrary.com | grep clojars
jakemccrary.com.	300	IN	TXT	"clojars jakemcc"
```

Thank you!

**Comment by danielcompton** [comment]
The group `com.jakemccrary` has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like. Thanks!
