### ISSUE TITLE
New Group Creation: org.alekcz

### ISSUE THREAD

**Issue by alekcz** [clojars/administration#116]
I am requesting verification of a new group. The group name is: `org.alekcz`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

If I it would also be possible to verify the group `alekcz` with my old releases that would be awesome.

Hope you're well. 

Alex

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.alekcz has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
