### ISSUE TITLE
info.senters group creation

### ISSUE THREAD

**Issue by rplevy** [clojars/administration#117]
I am requesting verification of a new group. The group name is: info.senters

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars rplevy`

![Screenshot from 2021-07-25 13-45-25](https://user-images.githubusercontent.com/358062/126912988-dd6e94b9-78b4-4eba-b636-996670a982c4.png)

**Comment by tobias** [comment]
Just checking in @rplevy - have you had a chance to look at this DNS configuration?
