### ISSUE TITLE
Verification request for new group "nl.jomco"

### ISSUE THREAD

**Issue by joodie** [clojars/administration#118]
I am requesting verification of a new group. The group name is: nl.jomco

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars joost`

**Comment by tobias** [comment]
The group https://clojars.org/groups/nl.jomco has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
