### ISSUE TITLE
Reverse domain name group verification request for com.owoga 

### ISSUE THREAD

**Issue by eihli** [clojars/administration#12]
I am requesting verification of a new group. The group name is: com.owoga

- [x] This group is a reverse-domain-based group
- [x] I have added a TXT DNS record for the domain that has a value of `clojars-12 eihli`

**Comment by tobias** [comment]
Hi @eihli! 

I'm not seeing the TXT record for `owoga.com`:

```
$ dig +short owoga.com TXT
owoga.ghost.io.
```

I would expect to see something similar to:

```
$ dig +short acceleratedtext.com TXT
"clojars-11 zm"
```

Can you confirm the TXT record was added to owoga.com?

**Comment by eihli** [comment]
I'm getting the same thing you're getting when I use the `+short` flag. 

Curiously, `dig owoga.com TXT` doesn't work either.

But with a full dig with ANY, I see it. Maybe something with TTL/cacheing? I just added this about 30 min ago. Something about setting DNS records I'm not familiar with?

```
➜  tightly-packed-trie git:(dev) ✗ dig owoga.com ANY

; <<>> DiG 9.16.12 <<>> owoga.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45517
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;owoga.com.                     IN      ANY

;; ANSWER SECTION:
owoga.com.              1799    IN      TXT     "clojars-12 eihli"
owoga.com.              60      IN      MX      1 aspmx.l.google.com.
owoga.com.              60      IN      MX      5 alt2.aspmx.l.google.com.
owoga.com.              3601    IN      SOA     dns1.registrar-servers.com. hostmaster.registrar-servers.com. 1614973773 43200 3600 604800 3601
owoga.com.              1800    IN      CNAME   owoga.ghost.io.
owoga.com.              1800    IN      NS      dns2.registrar-servers.com.
owoga.com.              1800    IN      NS      dns1.registrar-servers.com.
```
Something about `+short`?

**Comment by tobias** [comment]
Thanks for digging in a bit more - I tried with and without `+short`, with `@dns1.registrar-servers.com`, and with `ANY`, and still don't see it. I suspect it is a TTL somewhere. I'll give it some time and check tomorrow.

**Comment by tobias** [comment]
Thanks! 

The group `com.owoga` has been verified. There isn't (yet) a way to see that on the site, but I hope to add that soon. You can delete the TXT record if you like.
