### ISSUE TITLE
For new group `com.neuralgraphs`

### ISSUE THREAD

**Issue by lungsi** [clojars/administration#120]
I am requesting verification of a new group. The group name is `com.neuralgraphs`: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

```
# dog --type TXT --query neuralgraphs.com --short
"clojars lungsi"
```
Thank you.

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.neuralgraphs has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
