### ISSUE TITLE
New Group Creation: de.npexception

### ISSUE THREAD

**Issue by NPException** [clojars/administration#121]
I am requesting verification of a new group. The group name is: **de.npexception**

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars npexception`

In addition, I'd like to know how I can link my GitHub account to my Clojars account in order to get access to the group names **com.github.npexception** & **io.github.npexception**

**Comment by tobias** [comment]
The group https://clojars.org/groups/de.npexception has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

To verify and link your account to the com.github.npexception & io.github.npexception, you need to use the "Login with GitHub" option, and the email address on your Clojars account needs to be a verified address on your GitHub account.
