### ISSUE TITLE
New group: com.fbeyer

### ISSUE THREAD

**Issue by ferdinand-beyer** [clojars/administration#122]
I am requesting verification of a new group. The group name is: `com.fbeyer`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars fbeyer`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.fbeyer has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
