### ISSUE TITLE
lein new ctmx

### ISSUE THREAD

**Issue by whamtet** [clojars/administration#123]
I have forked `luminus/luminus-template` and would like to provide similar functionality `lein new ctmx` instead of `lein new luminus`.  I can deploy to `ctmx` fine, but would like to deploy to `ctmx/lein-template`.  Will clojars let me verify ctmx even though it is not a domain name?  Project is here https://github.com/whamtet/ctmx

**Comment by tobias** [comment]
Hi @whamtet:

Unfortunately we are only verifying domain-based groups, so the template will have to be under a domain-based group. Instructions for doing that are https://github.com/seancorfield/clj-new#general-template-usage and https://github.com/technomancy/leiningen/blob/master/doc/TEMPLATES.md#writing-templates. 

See https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq for the domain-based group names that are available to you by default if you don't want/don't have a domain to verify.
