### ISSUE TITLE
Group verification - polylith

### ISSUE THREAD

**Issue by tengstrand** [clojars/administration#124]
I am requesting verification of an existing group. The group name is: polylith

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
Hi @tengstrand:

We are only verifying [domain-based groups](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq). You can continue to deploy new versions of existing projects under `polylith`, but any new projects will need to be under a domain-based group.
