### ISSUE TITLE
Group Verification - com.github.polyfy.*

### ISSUE THREAD

**Issue by tengstrand** [clojars/administration#126]
I am requesting verification of a existing groups. The group names are:
com.github.polyfy.homebrew-polylith
com.github.polyfy.jline3
com.github.polyfy.polylith

- [x] These groups are [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
Hi @tengstrand! Can you create a repo at https://github.com/polyfy/clojars-verification-<your-clojars-username>? Once that is done, I can verify the subgroups. Thanks!

**Comment by tengstrand** [comment]
Done!

**Comment by tobias** [comment]
@tengstrand I'm not seeing the repo at https://github.com/orgs/polyfy/repositories - can you confirm it is a public repo?

**Comment by tengstrand** [comment]
Strange, I can see these repos using the link [https://github.com/orgs/polyfy/repositories](https://github.com/orgs/polyfy/repositories), even though I'm not logged in:
- jline3
- polylith
- home-brew-polylith

The polyfy access settings ([https://github.com/organizations/polyfy/settings/member_privileges](https://github.com/organizations/polyfy/settings/member_privileges):
<img width="1046" alt="polyfy-project-access" src="https://user-images.githubusercontent.com/631272/129254814-16a20928-0433-4d44-8d31-96085b2a560d.png">

When I check [https://github.com/polyfy/jline3/settings/access](https://github.com/polyfy/jline3/settings/access)
it looks like this:
<img width="1460" alt="polyfy-access" src="https://user-images.githubusercontent.com/631272/129254363-931e9192-b791-48e1-b700-cab3cb76b1e5.png">

**Comment by tobias** [comment]
Thanks!

The following groups have been verified and you should now see the "verified" badge when you view them on Clojars:

- https://clojars.org/groups/com.github.polyfy  
- https://clojars.org/groups/com.github.polyfy.homebrew-polylith
- https://clojars.org/groups/com.github.polyfy.jline3
- https://clojars.org/groups/com.github.polyfy.polylith

 You can delete the verification repo if you like.

**Comment by tobias** [comment]
Oops, that message was premature - I verified the `io.github.polyfy.*` set first by mistake, but you get both. I'll do the `com.*` versions now.

**Comment by tobias** [comment]
The `com.github.polyfy*` groups have been verified as well, so the full set is:

- https://clojars.org/groups/com.github.polyfy  
- https://clojars.org/groups/com.github.polyfy.homebrew-polylith
- https://clojars.org/groups/com.github.polyfy.jline3
- https://clojars.org/groups/com.github.polyfy.polylith
- https://clojars.org/groups/io.github.polyfy  
- https://clojars.org/groups/io.github.polyfy.homebrew-polylith
- https://clojars.org/groups/io.github.polyfy.jline3
- https://clojars.org/groups/io.github.polyfy.polylith

**Comment by tengstrand** [comment]
I could deploy to the jline3 repo now. Thank you very much for your help!

**Comment by tobias** [comment]
My pleasure! Glad we got it sorted out.
