### ISSUE TITLE
Group Verification for dev.glossa

### ISSUE THREAD

**Issue by semperos** [clojars/administration#127]
I am requesting verification of a new group. The group name is: `dev.glossa`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars semperos`

Thanks for your continued maintenance and development of Clojars!

**Comment by tobias** [comment]
Hi @semperos! 

The group https://clojars.org/groups/dev.glossa has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

Thanks for the kind words!
