### ISSUE TITLE
Group Verification - datum.md

### ISSUE THREAD

**Issue by bajrachar** [clojars/administration#128]
I am requesting verification of a [new] group. The group name is: datum.md

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars bajrachar`

**Comment by tobias** [comment]
The group https://clojars.org/groups/md.datum has been verified and you should now see the "verified" badge when you view it on Clojars. Note that the group is `md.datum` since the group is the reverse of the domain. You can delete the TXT record if you like.
