### ISSUE TITLE
New library under com.fulcrologic

### ISSUE THREAD

**Issue by awkay** [clojars/administration#129]
I am requesting verification of a [new | existing] group. The group name is: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

I'm unable to transfer the new artifact:

[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project datomic-cloud-backup: Failed to deploy artifacts: Could not transfer artifact com.fulcrologic:datomic-cloud-backup:jar:0.0.1 from/to clojars (https://clojars.org/repo): Authorization failed for https://clojars.org/repo/com/fulcrologic/datomic-cloud-backup/0.0.1/datomic-cloud-backup-0.0.1.jar 403 Forbidden - Group 'com.fulcrologic' isn't verified, so can't contain new projects (see https://git.io/JOs8J) -> [Help 1]

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.fulcrologic has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by awkay** [comment]
Thanks!
