### ISSUE TITLE
Verification of `world.convex` group id

### ISSUE THREAD

**Issue by helins** [clojars/administration#130]
I am requesting verification of a [new | existing] group (new on Clojars but already registered on Maven, owned by us: https://issues.sonatype.org/browse/OSSRH-68398). The group name is: `world.convex`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars convex`

**Comment by tobias** [comment]
The group https://clojars.org/groups/world.convex has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by helins** [comment]
I am affirmative it does not appear in verified group ids of the "convex" account. (I have registered groups before, I know where to look).

**Comment by helins** [comment]
The group got registered under account "mikera", which is the founder of convex.world, due to a mistake in the TXT record (was `clojars mikera` instead of `clojars convex` as mentioned in original post).

How can we transfer to the "convex" account?

**Comment by tobias** [comment]
@helins: mikera can add convex as a member of the admin group and it will be the same as convex having verified it. Is that an option?

**Comment by helins** [comment]
We'll give it a go, thanks!
