### ISSUE TITLE
Request for new group: com.github.clj-kondo

### ISSUE THREAD

**Issue by borkdude** [clojars/administration#131]
I am requesting verification of a new group. The group name is: com.github.clj-kondo.

The github org: https://github.com/clj-kondo

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)

**Comment by tobias** [comment]
Hi @borkdude! Can you create a public repository under the https://github.com/clj-kondo org called `clojars-verification-<your-clojars-username>` and let me know when that is available? That will verify ownership of the organization.

**Comment by borkdude** [comment]
@tobias https://github.com/clj-kondo/clojars-verification-borkdude

**Comment by borkdude** [comment]
Whoops, it was private, but now public.

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.github.clj-kondo has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the verification repo if you like.

**Comment by borkdude** [comment]
Thanks a lot.
