### ISSUE TITLE
please verify `com.brunobonacci`

### ISSUE THREAD

**Issue by BrunoBonacci** [clojars/administration#132]
I am requesting verification of an existing group. The group name is: `com.brunobonacci`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x]  I have added a TXT DNS record for the domain that has a value of `clojars brunobonacci`

I have one question, do I have to keep the TXT record in the DNS even after the verification is completed, or it is a one-off process and I can remove it?

thanks
Bruno

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.brunobonacci has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by BrunoBonacci** [comment]
thank you
