### ISSUE TITLE
Verify group xyz.jlicht for user jdlicht

### ISSUE THREAD

**Issue by jellelicht** [clojars/administration#137]
I am requesting verification of a new group. The group name is: xyz.jlicht

Note that the user is jdlicht, not jlicht! (Also me, but I seem to have lost access to the e-mailaccount linked to that clojars account).

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars jdlicht`

**Comment by tobias** [comment]
The group https://clojars.org/groups/xyz.jlicht has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
