### ISSUE TITLE
requesting verification for club.donutpower

### ISSUE THREAD

**Issue by flyingmachine** [clojars/administration#138]
I am requesting verification of a new group. The group name is `club.donutpower`: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars flyingmachine`

It'd be nice to have the group name "donutpower" if possible but it looks like that's no longer allowed?

**Comment by tobias** [comment]
Hi @flyingmachine!

Correct, we no longer allow new non-reverse-domain groups, sorry about that.

The group https://clojars.org/groups/club.donutpower has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
