### ISSUE TITLE
Verify com.github.clj-easy

### ISSUE THREAD

**Issue by borkdude** [clojars/administration#139]
I am requesting verification of a new group. The group name is: com.github.clj-easy

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)

See https://github.com/clj-easy. @ericdallo and I want to make libs there and publish them to clojars.

**Comment by tobias** [comment]
Hi @borkdude! Would you mind creating a public repo under the clj-easy organization called `clojars-verification-<your clojars username>`? That will be enough to verify ownership.

**Comment by borkdude** [comment]
Done: https://github.com/clj-easy/clojars-verification-borkdude

**Comment by borkdude** [comment]
Drat, same as last time, the repo was private. Now it's public.

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.github.clj-easy has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the verification repo if you like.

**Comment by borkdude** [comment]
Thanks!
