### ISSUE TITLE
org.pariyatti Group Verification

### ISSUE THREAD

**Issue by deobald** [clojars/administration#14]
I am requesting verification of a new group. The group name is: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars deobald'

## Questions:

1. I assume that second item in the checklist is referring to the integer id of this GitHub issue? I wanted to check before asking the sysadmin to create the TXT record.

2. Is it best for me to use `deobald`, my personal Clojars username, as I have above? Or should I create a Clojars username for the Pariyatti organization (https://github.com/pariyatti) ?

Thanks!
-steven

**Comment by tobias** [comment]
> I assume that second item in the checklist is referring to the integer id of this GitHub issue? I wanted to check before asking the sysadmin to create the TXT record.

It is, but after thinking about it, requiring the id provides no real value, so feel free to create the TXT record with `clojars deobald`. We've only done a few verifications so far, and are still figuring out this process. I've adjusted the issue template to no longer require the id.

> Is it best for me to use deobald, my personal Clojars username, as I have above? Or should I create a Clojars username for the Pariyatti organization (@pariyatti) ?

For existing groups, the username you provide has to be a member of the group. For new groups (as in this case), the username you provide will be the initial admin of the group, but can add other users as members or admins (the only difference between admins and members is admins can manage group membership - both can deploy to the group). So I would only create a username for the organization if you plan on using that account for deploys.

**Comment by deobald** [comment]
Thanks @tobias ! The TXT record for pariyatti.org has been created.

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/org.pariyatti has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
