### ISSUE TITLE
io.starkiller

### ISSUE THREAD

**Issue by csm** [clojars/administration#143]
I am requesting verification of a new group. The group name is: io.starkiller

- [✔️] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [✔️] I have added a TXT DNS record for the domain that has a value of `clojars csm`

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.starkiller has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
