### ISSUE TITLE
Delete account and group

### ISSUE THREAD

**Issue by khanhncm** [clojars/administration#144]
Hi Clojars,

Excuse me if my issue is not at the right repository. I did take a look, but still have no clue how to delete my account. So I do this issue.
Please help me delete my account khanhncm, the account associated  with my email khanhncm@outlook.com. You can use this email to verify me.
Also, please close or delete my group org.xvirus.

I appreciate your help.

**Comment by khanhncm** [comment]
Hi @tobias, thank for your attention
I have received your email, and have replied to confirm the deletion

**Comment by tobias** [comment]
Thanks for the confirmation @khanhncm - this has been done.
