### ISSUE TITLE
com.flexiana

### ISSUE THREAD

**Issue by parallelo3301** [clojars/administration#146]
I am requesting verification of an existing group. The group name is: `com.flexiana`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars flexiana`

Thank you

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.flexiana has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
