### ISSUE TITLE
New Group: com.hortau

### ISSUE THREAD

**Issue by hexadecy** [clojars/administration#147]
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain hortau.com that has a value of `clojars hexadecy`
- Our github: https://github.com/hortau
- Our website https://hortau.com

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.hortau has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
