### ISSUE TITLE
Verification for org.babashka

### ISSUE THREAD

**Issue by borkdude** [clojars/administration#148]
I am requesting verification of a new group. The group name is: org.babashka

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars borkdude`

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.babashka has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by borkdude** [comment]
Thanks @tobias !
