### ISSUE TITLE
Verify group com.computesoftware

### ISSUE THREAD

**Issue by kennyjwilli** [clojars/administration#149]
I am requesting verification of a [new | existing] group. The group name is: com.computesoftware

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars kennyjwilli`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.computesoftware has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
