### ISSUE TITLE
Group Verification for com.layerware

### ISSUE THREAD

**Issue by csummers** [clojars/administration#15]
I am requesting verification of an existing group. The group name is: `com.layerware`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars layerware`

**Comment by tobias** [comment]
Thanks! 

The group `com.layerware` has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
