### ISSUE TITLE
New group clj-commons.org

### ISSUE THREAD

**Issue by slipset** [clojars/administration#150]
I am requesting verification of a new  group. The group name is: 

clj-commons.org

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

I've added a TXT DNS record for `clj-commons.org` with the value `clojars erik` (I believe `erik` is my clojars username.

**Comment by tobias** [comment]
Hi @slipset - I'm not seeing any TXT records on clj-commons.org:

```
 dig txt clj-commons.org

; <<>> DiG 9.16.1-Ubuntu <<>> txt clj-commons.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 123
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;clj-commons.org.		IN	TXT

;; Query time: 24 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Sep 30 06:42:57 EDT 2021
;; MSG SIZE  rcvd: 44
```

can you double-check how you are setting it?

I also believe `erik` is your username: https://clojars.org/users/erik

**Comment by slipset** [comment]
![Screenshot 2021-09-30 at 12 45 32](https://user-images.githubusercontent.com/5894926/135441469-bbf2f5c5-203a-4207-9339-e7e1da52f76f.png)
Sorry about the language, but go daddy wants  speak Norwegian

**Comment by slipset** [comment]
Perhaps it should have an `@`` in  the `name` column?

**Comment by slipset** [comment]
That seemed to be it:
```12:48 $ dig txt clj-commons.org

; <<>> DiG 9.10.6 <<>> txt clj-commons.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54581
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;clj-commons.org.		IN	TXT

;; ANSWER SECTION:
clj-commons.org.	1800	IN	TXT	"clojars erik"

;; Query time: 111 msec
;; SERVER: 2001:4600:4:fff::253#53(2001:4600:4:fff::253)
;; WHEN: Thu Sep 30 12:48:39 CEST 2021
;; MSG SIZE  rcvd: 69

✔ ~
12:48 $
```

**Comment by tobias** [comment]
Yep, that fixed it! Having `clj-commons.org` in the `name` column added the record at `clj-commons.org.clj-commons.org`. 

The group https://clojars.org/groups/org.clj-commons has been verified and you should now see the "verified" badge on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by slipset** [comment]
Thanks! I'm totally useless in everything network.
