### ISSUE TITLE
New Group Verification Request

### ISSUE THREAD

**Issue by dehli** [clojars/administration#159]
I am requesting verification of a [new | existing] group. The group name is: `dev.dehli`. Thanks!

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars dehli`
  - [Link](https://mxtoolbox.com/SuperTool.aspx?action=txt%3a_clojars.dehli.dev&run=toolpage) 

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/dev.dehli has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
