### ISSUE TITLE
Group verification for com.github.bsless

### ISSUE THREAD

**Issue by bsless** [clojars/administration#16]
I am requesting verification of a new group. The group name is: com.github.bsless

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

It wasn't set up automatically because when I set up my Clojars account I didn't sign up via Github.

If this isn't possible I'll settle for the existing Clojars groups

Thanks,
Ben

**Comment by tobias** [comment]
Hi @bsless! The "Login with GitHub" feature will still verify that group for you when you log in to Clojars using that method as long as your Clojars email address is one of the verified emails on your GitHub account. Can you give that a try and let me know if it does verify the group? If it works, you should see it listed on your dashboard page as verified.

(Note: logging in with GitHub was temporarily broken until a few minutes ago, so if you got a stack trace when trying earlier, please try again now)

**Comment by bsless** [comment]
works now, thanks!
Closing the issue :)
