### ISSUE TITLE
Please help with with group verification district0x

### ISSUE THREAD

**Issue by sm47916** [clojars/administration#165]
I am requesting verification of an existing group. The group name is: `district0x`
- https://clojars.org/groups/district0x
- https://github.com/district0x

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`) (This group bases on Github org, but the name is not set to github reverse dns)
- [x] I have created a public repository under that group named `clojars-district0x` (https://github.com/district0x/clojars-district0x)

**Comment by sm47916** [comment]
Hi, thanks for your answer! Can we then please proceed with the `{com|io}.github.district0x`  groups verification? Please let me know the name of the project that I need to create for this. There's already https://github.com/district0x/clojars-district0x created.

**Comment by tobias** [comment]
Sounds good @sm47916 - can you rename the https://github.com/district0x/clojars-district0x project to `clojars-<your-clojars-username>? That makes it clear what Clojars account should own the new groups.

**Comment by sm47916** [comment]
Hi, I assume our clojars username is travis-cd, I renamed the project to match that: https://github.com/district0x/clojars-travis-cd

**Comment by tobias** [comment]
Hi @sm47916 - is that the user you use to log in to Clojars with? Ideally, it would be one that you do log in with, and you can then invite other users to the group, which gives them deploy rights. If you do log in and manage groups with `travis-cd`, that will work. Please let me know if you want to proceed with `travis-cd`.

**Comment by sm47916** [comment]
Hi @tobias,  the `travis-cd` is just a login that we use to push jars from our ci system. Unfortunately, this is not what we need. 
Ideally, we'd like to verify a group name that has a match to the name of our Github org, e.g.`io.github.district0x` or just `district0x`. I can create TXT records or any repositories to support verification.

**Comment by tobias** [comment]
Hi @sm47916. I apologize for the confusion here. To clarify:

- the presence of a repo named like `clojars-<a clojars username>` under the `district0x` group is enough to verify `(com|io).github.district0x`
- the username given as part of that repo name is used as the initial member of the new groups, and that user can then log in to invite other users to that group, so is typically a person's username, not a bot username

I've gone ahead and verified `com.github.district0x` and `io.github.district0x` with `travis-cd` as the sole member so you aren't held up with releasing. If you don't have permission to log in as `travis-cd` and need other users added as members, please let me know and I can make that happen.

**Comment by sm47916** [comment]
Thanks! I can see them verified now. Looks like I have permission to manage users in those groups. Thanks a lot for your help!

**Comment by tobias** [comment]
My pleasure @sm47916!
