### ISSUE TITLE
New group creation 

### ISSUE THREAD

**Issue by tkaryadis** [clojars/administration#166]
I am requesting verification of a new group. The group name is:  org.cmql

I own the domain name http://cmql.org/
[Screenshot from namecheap site showing that i am the owner](https://postimg.cc/Wh23ftFS)

My clojars username = takis  (i log in with github)
My Groups
com.github.tkaryadis   verified
io.github.tkaryadis       verified
net.clojars.takis           verified
org.clojars.takis           verified

[screnshot from my acount details](https://postimg.cc/V0sRKMxn)

*i have another acount on clojars with username(tkaryadis) but i dont use it(i registered on clojars website in the past with it)
 i want the new group to be created on my github acount on username takis

Thank you

From WHOIS
Domain Name: CMQL.ORG
Registry Domain ID: D402200000018247389-LROR
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: http://www.namecheap.com
Updated Date: 2021-11-04T19:16:19Z
Creation Date: 2021-11-04T18:45:16Z
Registry Expiry Date: 2022-11-04T18:45:16Z
Registrar Registration Expiration Date:
Registrar: NameCheap, Inc.
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
Reseller:
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: addPeriod https://icann.org/epp#addPeriod
Registrant Organization: Privacy service provided by Withheld for Privacy ehf
Registrant State/Province: Capital Region
Registrant Country: IS
Name Server: HYDROGEN.NS.HETZNER.COM
Name Server: OXYGEN.NS.HETZNER.COM
Name Server: HELIUM.NS.HETZNER.DE
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form https://www.icann.org/wicf/)
>>> Last update of WHOIS database: 2021-11-07T03:01:13Z <<<

**Comment by tobias** [comment]
Hi @tkaryadis! The preferred way to verify domain-based groups is to use a TXT DNS record. Can you add a TXT record to the DNS for `cmql.org` with `clojars takis` as the value (see https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-do-i-verify-a-group-name)?

**Comment by tkaryadis** [comment]
I am sorry i didn't know what to do, now i think its ok.

I added the TXT dns record
[added the dns record](https://postimg.cc/47Y9LwNj)

I checked it with  $dig -t txt cmql.org
and i got this, so looks like its working

[dig check](https://postimg.cc/XrNX1xsx)

Thank you

**Comment by tobias** [comment]
No problem @tkaryadis. 

The group https://clojars.org/groups/org.cmql has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
