### ISSUE TITLE
Group Verification for org.soulspace and org.soulspace.clj

### ISSUE THREAD

**Issue by lsolbach** [clojars/administration#167]
I am requesting verification of a [new | existing] group. The group names are: org.soulspace and org.soulspace.clj

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars lsolbach` (to soulspace.org)

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

**Comment by tobias** [comment]
The groups https://clojars.org/groups/org.soulspace and https://clojars.org/groups/org.soulspace.clj have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the TXT record if you like.
