### ISSUE TITLE
Group Verification / New Group Creation for ENS domains

### ISSUE THREAD

**Issue by matthewdowney** [clojars/administration#169]
Hi there, 

I hope this isn't too out of place / beyond scope, but I wanted to propose a mechanism for verifying [Ethereum Name Service](https://docs.ens.domains/) domains for group verification in a similar manner to verification for DNS.

For example, I own the mjd.eth domain and would like to be able to use the group id `eth.mjd`. 

Ownership of that ENS domain can be verified by:

1. Checking [the registrant for mjd.eth](https://app.ens.domains/name/mjd.eth/details) (you could also interact with the ENS smart contract directly to look up the registrant address for a specific domain). 
2. Having the registrant sign a message "clojars <clojars username>" with the same key that registered the address. E.g. I signed "clojars mjdowney" with the key that I used to register mjd.eth:
```
{
  "address": "0x10459a52094b4dd18320378df3bb2b8d0e81234a",
  "msg": "0x636c6f6a617273206d6a646f776e6579",
  "sig": "5ea4eb8ae6d6ee3bf725b5796e7964425a17969850c134ebe651f4bf5fc462fe3c61d41453894f69ec7e1f79dc65dd3839aaade9ebb7833e8ad182c214c03be81b"
}
```
3. Checking (e.g. with [this tool ](https://www.myetherwallet.com/tools?tool=verify) or [this one](https://etherscan.io/verifySig)) that the signature is valid.

What do y'all think? Is granting group id based on ENS registration desirable, and if so, is this mechanism workable?

**Comment by tobias** [comment]
Hi @matthewdowney. Apologies for the delayed response, we've been thinking about this a bit. I appreciate your thoughtful proposal, but the answer is "not right now" for the following reasons:

- we feel like the DNS and repo verification options give quite a bit of flexibility
- supporting ENS would impose extra work on our volunteer admins
- I don't want to encourage the use of any proof-of-work blockchain for environmental reasons (though I understand that ETH is moving to proof-of-stake, which may change my opinion)

**Comment by matthewdowney** [comment]
Hey Toby, I totally understand. Thanks for considering it!

**Comment by matthewdowney** [comment]
Hey @tobias , no pressure here, but wanted to check if ETH's completed move to proof of stake affects this decision. Thanks!

**Comment by danielcompton** [comment]
@matthewdowney I don't know a lot about this space, but what's to stop someone creating a .eth TLD in the future which is just a "regular" domain, not an ENS domain? How would you envision handling name conflicts? Or would you add some prefix to ENS domains to separate them?

**Comment by matthewdowney** [comment]
Hey good point! I mistakenly thought they had registered .eth with ICANN but I understand from [this medium post](https://medium.com/the-ethereum-name-service/why-ens-doesnt-create-more-tlds-responsible-citizenship-in-the-global-namespace-7e66658fe2b1) that they have not, and that it's only a future goal. 

Fwiw [Brave browser's strategy](https://brave.com/brave-crypto-dns-strategy/) includes rules which recognize .eth domains, and it's gaining steam as a way to point to [IPFS](https://brave.com/brave-integrates-ipfs/) content, but it's always possible that ICANN decides to give .eth to Ethiopia (currently .et).
