### ISSUE TITLE
New group "se.w3t"

### ISSUE THREAD

**Issue by zertan** [clojars/administration#171]
I am requesting verification of a new group. The group name is: se.w3t

- [x ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ x ] I have added a TXT DNS record for the domain that has a value of `clojars zertan`

**Comment by tobias** [comment]
The group https://clojars.org/groups/se.w3t has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
