### ISSUE TITLE
Verification for com.hypalynx

### ISSUE THREAD

**Issue by mikepjb** [clojars/administration#172]
I am requesting verification of a new group. The group name is: com.hypalynx

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars mikepjb`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.hypalynx has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
