### ISSUE TITLE
New Group Creation: house.jux

### ISSUE THREAD

**Issue by klauswuestefeld** [clojars/administration#173]
I am requesting verification of a new group. The group name is: house.jux

This group is a reverse-domain-based group
I have added a TXT DNS record for the jux.house domain that has a value of `clojars klauswuestefeld`

**Comment by tobias** [comment]
The group https://clojars.org/groups/house.jux has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
