### ISSUE TITLE
https://clojars.org/groups/com.platform

### ISSUE THREAD

**Issue by nitishgoyal13** [clojars/administration#174]
I am requesting verification of a [new | existing] group. The group name is: com.platform

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <>`

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

**Comment by tobias** [comment]
Hi @nitishgoyal13 - I don't see the appropriate TXT record for `platform.com`. Please let me know when you have added it.

**Comment by tobias** [comment]
I'm closing this, but feel free to reopen @nitishgoyal13 when you have set the TXT record or want to discuss further.
