### ISSUE TITLE
New group `dev.samps`

### ISSUE THREAD

**Issue by lsmag** [clojars/administration#175]
I am requesting verification of a new group. The group name is: `dev.samps`

- [ X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ X] I have added a TXT DNS record for the domain that has a value of `clojars samps`

**Comment by tobias** [comment]
The group https://clojars.org/groups/dev.samps has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
