### ISSUE TITLE
kosmos

### ISSUE THREAD

**Issue by pupcus** [clojars/administration#177]
I am requesting verification of a [existing] group. The group name is: kosmos

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

I am not sure which of these apply but I have several projects including `kosmos` itself along with `kosmos/<sub-project>` repositories that push various pieces of the kosmos system to clojars.  THIS particular project that I am trying to push is named `kosmos/kairos` and is a task/fn scheduling sub-project. The `kosmos` system is based on the component library and starts system components (like web servers, database connections, embedded repls, schedulers, etc) automatically based on an edn file description of the system.

**Comment by tobias** [comment]
Hi @pupcus:

The group `kosmos` isn't domain-based, so unfortunately can't be verified. You can continue to push new versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. 

If you don't have a domain to use for the new group, there are several other options available - please see the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#do-i-have-to-have-my-own-domain-name-to-publish-to-clojars).
