### ISSUE TITLE
Requesting verification of an existing group: ua.kasta

### ISSUE THREAD

**Issue by piranha** [clojars/administration#178]
I am requesting verification of an existing group. The group name is: ua.kasta

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars asolovyov`

**Comment by tobias** [comment]
The group https://clojars.org/groups/ua.kasta has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
