### ISSUE TITLE
Group verification for org.endot

### ISSUE THREAD

**Issue by justone** [clojars/administration#18]
I am requesting verification of a new group. The group name is `org.endot`:

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars ndj`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/org.endot has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
