### ISSUE TITLE
Verification of me.ebbinghaus

### ISSUE THREAD

**Issue by MrEbbinghaus** [clojars/administration#180]
I am requesting verification of a new group. The group name is: `me.ebbinghaus`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Also: 
How can I verify the group: `com.github.mrebbinghaus` if I don't have a GitHub based Clojars Account? 
Can I migrate or merge accounts?

**Comment by tobias** [comment]
The group https://clojars.org/groups/me.ebbinghaus has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

To verify `com.github.mrebbinghaus`, you just need the email on your Clojars account to be one of the verified emails on your GitHub account, then log in to Clojars via GitHub. There aren't a separate class off accounts for logging in via GitHub - we just use that auth flow to look up the Clojars email.

**Comment by MrEbbinghaus** [comment]
It worked, thank you. :-)
