### ISSUE TITLE
New group name: sino.study

### ISSUE THREAD

**Issue by simongray** [clojars/administration#182]
I am requesting verification of a new group. The group name is: study.sino

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars simongray`

**Comment by simongray** [comment]
https://mxtoolbox.com/SuperTool.aspx?action=txt%3asino.study&run=toolpage

**Comment by tobias** [comment]
The group https://clojars.org/groups/study.sino has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
