### ISSUE TITLE
Group verification for org.naturallexicon.ont-app

### ISSUE THREAD

**Issue by ont-app** [clojars/administration#184]
I am requesting verification of a new group. The group name is: org.naturallexicon.ont-app

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars eric-scott`

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.naturallexicon.ont-app has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by ont-app** [comment]
Thanks!
