### ISSUE TITLE
Verification of new reverse-domain-based group: `net.gered`

### ISSUE THREAD

**Issue by gered** [clojars/administration#185]
I am requesting verification of a new group. The group name is: `net.gered`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars gered`

**Comment by tobias** [comment]
The group https://clojars.org/groups/net.gered has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by gered** [comment]
Thanks a bunch!
