### ISSUE TITLE
com.github.omkamra

### ISSUE THREAD

**Issue by cellux** [clojars/administration#186]
I am requesting verification of a new group. The group name is: `com.github.omkamra`

- [x] This group is based on a GitHub organization: `com.github.omkamra`
- [x] I have created a public repository under that group named `clojars-cellux`

**Comment by tobias** [comment]
The groups https://clojars.org/groups/com.github.omkamra and https://clojars.org/groups/io.github.omkamra have been verified (you get both for a GitHub org-based group) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
