### ISSUE TITLE
New reverse-domain-based group: org.pilosus

### ISSUE THREAD

**Issue by pilosus** [clojars/administration#187]
I am requesting verification of a new group. The group name is: `org.pilosus`

- [+] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [+] I have added a TXT DNS record for the domain that has a value of `clojars vrs`

```
$ dig TXT pilosus.org | grep clojars
pilosus.org.		3442	IN	TXT	"clojars vrs"
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.pilosus has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
