### ISSUE TITLE
Verification of io.randomseed

### ISSUE THREAD

**Issue by siefca** [clojars/administration#188]
I am requesting verification of an existing group. The group name is: io.randomseed

- This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- I have added a TXT DNS record for the domain that has a value of `clojars siefca`

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.randomseed has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
