### ISSUE TITLE
Verification of the group "ch.codesmith"

### ISSUE THREAD

**Issue by stanislas** [clojars/administration#189]
I am requesting verification of a new group. The group name is: ch.codesmith

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars stanhbb`

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

**Comment by stanislas** [comment]
Thank you and happy new year! ;)

**Comment by stanislas** [comment]
```
> dig -t txt codesmith.ch

; <<>> DiG 9.10.6 <<>> -t txt codesmith.ch
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51328
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;codesmith.ch.			IN	TXT

;; ANSWER SECTION:
codesmith.ch.		3600	IN	TXT	"clojars stanhbb"
codesmith.ch.		3600	IN	TXT	"v=spf1 include:spf.messagingengine.com ?all"
codesmith.ch.		3600	IN	TXT	"google-site-verification=3G5gfxVozCPYL7LvHQYxoRbX12JPoIB6Jzj_iVhNBKY"

;; Query time: 29 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Sun Jan 02 15:55:37 CET 2022
;; MSG SIZE  rcvd: 206
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/ch.codesmith has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

And happy new year to you as well!

**Comment by stanislas** [comment]
thank you very much! it is working perfectly
