### ISSUE TITLE
Group Verification: com.signal-ai

### ISSUE THREAD

**Issue by Limess** [clojars/administration#19]
I am requesting verification of a new group. The group name is `com.signal-ai`

The clojars username is `signalops`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars signalops`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/com.signal-ai has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
