### ISSUE TITLE
Group Verification: com.oscaro

### ISSUE THREAD

**Issue by iomonad** [clojars/administration#190]
I am requesting verification of a existing group. The group name is: `com.oscaro`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars iomonad`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.oscaro has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by iomonad** [comment]
Thanks a lot.
