### ISSUE TITLE
Request to verify new group com.code-intelligence

### ISSUE THREAD

**Issue by sebastianpoeplau** [clojars/administration#191]
I am requesting verification of a new group. The group name is: com.code-intelligence

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars poeplau-ci`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.code-intelligence has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by sebastianpoeplau** [comment]
Works, thanks for the fast reaction!

**Comment by tobias** [comment]
My pleasure!
