### ISSUE TITLE
Please verify my io.titanoboa and io.titanoboa.tasklet groups

### ISSUE THREAD

**Issue by mikub** [clojars/administration#192]
Hi there~

I am requesting verification of  existing groups. Please verify my `io.titanoboa` and `io.titanoboa.tasklet` groups

- [X] I have added a TXT DNS record for the domain that has a value of `clojars miro`

Cheers
Miro

**Comment by tobias** [comment]
The groups https://clojars.org/groups/io.titanoboa and https://clojars.org/groups/io.titanoboa.tasklet have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by mikub** [comment]
Thanks @tobias !

**Comment by tobias** [comment]
My pleasure!
