### ISSUE TITLE
New group com.github.discljord for the Discljord project

### ISSUE THREAD

**Issue by IGJoshua** [clojars/administration#193]
I am requesting verification of a new group. The group name is: com.github.discljord

- [x] This group is based on a GitHub or GitLab organization (ex: https://github.com/discljord -> `com.github.discljord`)
- [x] I have created a public repository under that group named `clojars-suskeyhose` and `clojars-johnnyjayjay`

**Comment by tobias** [comment]
The groups com.github.discljord and io.github.discljord (you get both!) have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. 

I only saw the https://github.com/discljord/clojars-suskeyhose repo, so only the suskeyhose user is a member of the groups. But you can log in as that user and add johnnyjayjay as a member.

You can delete the verification repo if you like.
