### ISSUE TITLE
"protojure" group

### ISSUE THREAD

**Issue by ghaskins** [clojars/administration#194]
I am requesting verification of a [new | existing] group. The group name is: protojure

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [X] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [X] I have created a public repository under that group named `clojars-<your clojars username>`

https://github.com/protojure/clojars-ghaskins

**Comment by tobias** [comment]
The groups `com.github.protojure` and `io.github.protojure` (you get both) have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
