### ISSUE TITLE
New group creation: io.github.kit-clj

### ISSUE THREAD

**Issue by nikolap** [clojars/administration#195]
I am requesting verification of a new group. The group name is: io.github.kit-clj

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [x] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`) https://kit-clj.github.io/ https://github.com/kit-clj
- [x] I have created a public repository under that group named `clojars-nperic` https://github.com/kit-clj/clojars-nperic

**Comment by tobias** [comment]
The groups io.github.kit-clj & com.github.kit-clj (you get both when verifying a github org) have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
