### ISSUE TITLE
New group request: net.jarpy

### ISSUE THREAD

**Issue by jarpy** [clojars/administration#196]
I am requesting verification of a new group. The group name is: `net.jarpy`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars jarpy`

**Comment by tobias** [comment]
The group https://clojars.org/groups/net.jarpy has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
