### ISSUE TITLE
Requesting verifications for "com.teachbanzai"

### ISSUE THREAD

**Issue by kendagriff** [clojars/administration#197]
I am requesting verification of a [new | existing] group. The group name is: **com.teachbanzai**

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars buchanankendall` (`clojars.teachbanzai.com`)

**Comment by tobias** [comment]
The group com.teachbanzai has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
