### ISSUE TITLE
com.wotbrew verification

### ISSUE THREAD

**Issue by wotbrew** [clojars/administration#198]
I am requesting verification of an existing group. The group name is: com.wotbrew

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars wotbrew`

**Comment by tobias** [comment]
The group com.wotbrew has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
