### ISSUE TITLE
Verifing lambda-toolshed organization

### ISSUE THREAD

**Issue by stevenproctor** [clojars/administration#199]
I am requesting verification of a new group. The group name is: `lambda-toolshed`

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [X] This group is based on a GitHub or GitLab organization (ex: https://github.com/lambda-toolshed -> `io.github.lambda-toolshed`)
- [X] I have created a public repository under that group named `clojars-proctorit`

**Comment by tobias** [comment]
The groups https://clojars.org/groups/com.github.lambda-toolshed and https://clojars.org/groups/io.github.lambda-toolshed (you get both) have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.

**Comment by stevenproctor** [comment]
👍 

Thanks so much!
