### ISSUE TITLE
Verify holyjak.cz

### ISSUE THREAD

**Issue by holyjak** [clojars/administration#20]
I am requesting verification of a new group. The group name is: cz.holyjak

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars holyjak`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/cz.holyjak has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by holyjak** [comment]
Thanks a lot!
