### ISSUE TITLE
Requesting verification of `com.nytimes`

### ISSUE THREAD

**Issue by jvia** [clojars/administration#200]
I am requesting verification of an existing group. The group name is: `com.nytimes`.

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

**Comment by tobias** [comment]
Hi @jvia! 

I don't yet see a clojars TXT record on nytimes.com. Let me know when you are able to get that added. If it helps with navigating IT, you can also add the TXT record to the clojars.nytimes.com subdomain, and the TXT record (at either domain) can be removed once verification is complete.

**Comment by jvia** [comment]
Hi @tobias, I will get back to you!

**Comment by jvia** [comment]
Hi @tobias, could you please confirm?

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.nytimes has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by jvia** [comment]
Thank you!
