### ISSUE TITLE
create new group: com.ensime

### ISSUE THREAD

**Issue by kornev** [clojars/administration#201]
I am requesting verification of a new group. The group name is: com.ensime

- [x] This group is a com.ensime (https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of  `clojars-kornev`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.ensime has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
