### ISSUE TITLE
Requesting verification of group net.modulolotus

### ISSUE THREAD

**Issue by KingMob** [clojars/administration#205]
I am requesting verification of a [new | existing] group. The group name is: net.modulolotus

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/net.modulolotus has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by KingMob** [comment]
Thanks @tobias!
