### ISSUE TITLE
Creation of new groups "under" com.7theta

### ISSUE THREAD

**Issue by sandhu** [clojars/administration#207]
I own `7theta.com` and the `com.7theta` group was verified in #8 

In order to be able to publish `leiningen` templates, I need to use different group names for each one.

Could you please create the following groups:

- `com.7theta.template.lib`
- `com.7theta.template.web`
- `com.7theta.template.mobile`

Thank you.

**Comment by tobias** [comment]
Hi @sandhu - these three groups have been created and verified:
![image](https://user-images.githubusercontent.com/2631/154061646-cac641b9-ac4d-475a-a97d-21037d3de28c.png)

**Comment by sandhu** [comment]
Thank you @tobias. Very much appreciated.

**Comment by tobias** [comment]
My pleasure!
