### ISSUE TITLE
vivid/art-cli

### ISSUE THREAD

**Issue by enspritz** [clojars/administration#209]
I am requesting verification of a [new | existing] group. The group name is: `vivid/art-cli`

Releasing version 0.6.0, this request is for a new intermediate dependency for the existing `vivid/art` called `vivid/art-cli`.

Thanks!

---- 8< ----

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

**Comment by tobias** [comment]
The group `vivid` isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. 

If you don't have a domain to use for the group, there are several other options available - please see the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#do-i-have-to-have-my-own-domain-name-to-publish-to-clojars).

**Comment by enspritz** [comment]
Thanks @tobias for responding. For better or for worse, our domain name has a hyphen in it, which complicates the namespacing, particularly with Java. Is there any leeway given our grandfathering `vivid/art` and the `vivid/{boot,clj,lein}-art` names?

**Comment by tobias** [comment]
Hi @enspritz - we aren't providing any leeway for new project names, unfortunately.

However, their is no requirement that the group name is used in the namespaces provided by the jar. You can call the project `net.vivid-inc/art-cli`. but have the namepsaces be `vivid.art.cli`, etc if you want to avoid hyphens in the namespace names.

Does that work?

**Comment by enspritz** [comment]
Hi @tobias and thanks. I'm thinking along the same lines. Will try `net.vivid-inc/art-cli` and see how it goes. We can close this particular item.

**Comment by tobias** [comment]
Sounds good @enspritz. Please open a new issue when you are ready to verify `net.vivid-art`.
