### ISSUE TITLE
Verify nl.epij

### ISSUE THREAD

**Issue by pepijn** [clojars/administration#21]
I am requesting verification of an existing group. The group name is: `nl.epij`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars pp`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/nl.epij has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by pepijn** [comment]
Thank you!
