### ISSUE TITLE
Verify `net.vemv`

### ISSUE THREAD

**Issue by vemv** [clojars/administration#211]
I am requesting verification of an existing group. The group name is: `net.vemv`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Thanks!

-V

**Comment by tobias** [comment]
The group https://clojars.org/groups/net.vemv has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by vemv** [comment]
Cheers 🍻
