### ISSUE TITLE
Please create com.deercreeklabs group

### ISSUE THREAD

**Issue by chadharrington** [clojars/administration#212]
I am requesting verification of a [new | existing] group. The group name is: com.deercreeklabs

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Please advise if I need to do anything else. Thanks!

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.deercreeklabs has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
