### ISSUE TITLE
New Group Creation request for polycode.fi

### ISSUE THREAD

**Issue by esuomi** [clojars/administration#213]
I am requesting verification of a new group. The group name is: `fi.polycode`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

NOTE: The domain's TXT DNS record has other entries as well, the requested one is the latest/last  one.

**Comment by tobias** [comment]
The group https://clojars.org/groups/fi.polycode has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
