### ISSUE TITLE
New group creation, ai.mypulse

### ISSUE THREAD

**Issue by jordanrobinson** [clojars/administration#215]
I am requesting verification of a new group. The group name is: ai.mypulse

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars jordanrobinson`

Please let me know if any questions or further information needed. I've set up the TXT record but if there's any issues with it let me know and I'll rectify asap.

Thanks,
Jordan

**Comment by tobias** [comment]
Everything looks good @jordanrobinson!

The group https://clojars.org/groups/ai.mypulse has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
