### ISSUE TITLE
com.wallbrew verification

### ISSUE THREAD

**Issue by nnichols** [clojars/administration#22]
I am requesting verification of an existing group. The group name is: `com.wallbrew`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain (wallbrew.com) that has a value of `clojars nnichols`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/com.wallbrew has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
