### ISSUE TITLE
Verify com.stuartsierra

### ISSUE THREAD

**Issue by stuartsierra** [clojars/administration#220]
I am requesting verification of an **existing** group. The group name is: `com.stuartsierra`

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars stuartsierra`

Thanks for keeping Clojars safe and available for the Clojure community!

**Comment by tobias** [comment]
Hi Stuart! 

he group https://clojars.org/groups/com.stuartsierra has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

> Thanks for keeping Clojars safe and available for the Clojure community!

My pleasure!
