### ISSUE TITLE
Group name verification  net.xlfe

### ISSUE THREAD

**Issue by xlfe** [clojars/administration#225]
I am requesting verification of a new group. The group name is: net.xlfe

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars xlfe`

Thanks for keeping Clojars safe and available for the Clojure community!

**Comment by tobias** [comment]
The group `net.xlfe` has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
