### ISSUE TITLE
Verify group kelveden

### ISSUE THREAD

**Issue by kelveden** [clojars/administration#226]
I am requesting verification of a existing group. The group name is: kelveden

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [x] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-kelveden` - https://github.com/kelveden/clojars-kelveden

**Comment by tobias** [comment]
The group `kelveden` isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. 

If you don't have a domain to use for the group, there are several other options available - please see the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#do-i-have-to-have-my-own-domain-name-to-publish-to-clojars).

If you are asking to verify `io.github.kelveden` and `com.github.kelveden`, you can auto-verify those groups by using "Login with GitHub" on https://clojars.org/login if the email associated with your clojars account is a verified email on your GitHub account.

**Comment by kelveden** [comment]
Ah ok understood; thanks @tobias.
