### ISSUE TITLE
Requesting verification of a new group: is.mad

### ISSUE THREAD

**Issue by madis** [clojars/administration#227]
I am requesting verification of a new group. The group name is: `is.mad`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

```
$ nslookup -type=txt mad.is
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
mad.is	text = "clojars madis"
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/is.mad has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
