### ISSUE TITLE
Verify cn.leancloud

### ISSUE THREAD

**Issue by liuchong** [clojars/administration#23]
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars liuchong`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/cn.leancloud has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
