### ISSUE TITLE
a new group com.github.redhatqe to create and verify

### ISSUE THREAD

**Issue by jstavel** [clojars/administration#231]
I am requesting verification of a new group. The group name is: com.github.redhatqe

- [x] This group is based on a GitHub organization https://github.com/RedHatQE -> `com.github.redhatqe`
- [x] I have created a public repository under that group named `clojars-jstavel`

**Comment by tobias** [comment]
The groups com.github.redhatqe & io.github.redhatqe have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
