### ISSUE TITLE
Verify Clojar Library

### ISSUE THREAD

**Issue by segan23** [clojars/administration#234]
I am requesting verification of an existing group. The group name is: circleci

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [x] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-<your clojars username>` (https://github.com/circleci/clojars-segan23)

**Comment by tobias** [comment]
The group `circleci` isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. 

Using a GitHub repository for verification verifies `com.github.circleci` and `io.github.circleci` as groups - are you requesting that those be verified?

**Comment by segan23** [comment]
Yes requesting verification as groups.

**Comment by tobias** [comment]
Sounds good. I can verify the `com.github` and `io.github` groups. But I just noticed that there is no `segan23` user on clojars.org - can you update the repository name to match the name of your clojars.org account?

Also note that CircleCI already has [a verified group of `com.circleci`](https://clojars.org/groups/com.circleci), in case you weren't aware.

**Comment by segan23** [comment]
Updated repo to make clojar account https://github.com/circleci/clojars-circleci_secops

We do have a verified com.cirlceci, but we also have a circleci group:

![image](https://user-images.githubusercontent.com/82829668/160428099-d615bd5f-378a-47a3-b2cf-9bb758309eea.png)

Are we good to verify that group with this information?

**Comment by tobias** [comment]
The groups com.github.circleci & io.github.circleci have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.

The group `circleci` isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. Please see the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#do-i-have-to-have-my-own-domain-name-to-publish-to-clojars).
