### ISSUE TITLE
Group name verfication: de.active-group

### ISSUE THREAD

**Issue by dfrese** [clojars/administration#236]
I am requesting verification of a [new | existing] group. The group name is: de.active-group

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars dfrese`

**Comment by tobias** [comment]
The group https://clojars.org/groups/de.active-group has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
