### ISSUE TITLE
Verify ownership of group `co.collbox` by user `camdez`

### ISSUE THREAD

**Issue by camdez** [clojars/administration#237]
I am requesting verification of an existing group. The group name is: `collbox`

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [x] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-<your clojars username>`

Thanks!

**Comment by tobias** [comment]
The group `collbox`  isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. Please see the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#do-i-have-to-have-my-own-domain-name-to-publish-to-clojars).

Providing a GitHub repo for verification will give you access to the groups `io.github.collbox` and `com.github.collbox` - is that what you are requesting verification of?

**Comment by camdez** [comment]
@tobias Thanks for the quick response. In that case, let's verify the `co.collbox` group instead.

I am requesting verification of an existing group. The group name is: `co.collbox`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [ ] This group is based on a GitHub or GitLab organization (ex: https://github.com/foo -> `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`

**Comment by tobias** [comment]
The group `co.collbox` has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by camdez** [comment]
@tobias Thank you!
