### ISSUE TITLE
Verify ownership of io.operatr

### ISSUE THREAD

**Issue by wavejumper** [clojars/administration#239]
I am requesting verification of a **new** group. The group name is: `io.operatr`

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars crowley`

**Comment by tobias** [comment]
The group `io.operatr` has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
