### ISSUE TITLE
Verification io.replikativ

### ISSUE THREAD

**Issue by TimoKramer** [clojars/administration#24]
I am requesting verification of an existing group. The group name is: `io.replikativ`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars timokramer`

Thank you!

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/io.replikativ has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
