### ISSUE TITLE
Group Verification: info.sunng

### ISSUE THREAD

**Issue by sunng87** [clojars/administration#241]
I am requesting verification of a existing group. The group name is: `info.sunng`

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/info.sunng has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
