### ISSUE TITLE
Group verification for org.uncomplicate

### ISSUE THREAD

**Issue by blueberry** [clojars/administration#242]
I am requesting verification of a [new | existing] group. The group name is: org.uncomplicate

- [x ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x ] I have added a TXT DNS record for the domain that has a value of `clojars dragandj`

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.uncomplicate has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by blueberry** [comment]
Thank you.
