### ISSUE TITLE
Verify run.avelino

### ISSUE THREAD

**Issue by avelino** [clojars/administration#243]
I am requesting verification of a [new | existing] group. The group name is: `run.avelino`

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars avelino`

Thanks for keeping Clojars safe and available for the Clojure community!

**Comment by tobias** [comment]
The group https://clojars.org/groups/run.avelino has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
