### ISSUE TITLE
Group Verification

### ISSUE THREAD

**Issue by jackrusher** [clojars/administration#244]
- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.com` / `io.github.foo`)
- [X] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

I assume by "username" in the above, you mean the group id? Or should I have created `clojars-jackrusher` to verify the `applied-science` group?

https://github.com/applied-science/clojars-applied-science

**Comment by jackrusher** [comment]
It's not a new group, but I've renamed the repo as you requested. :)

**Comment by tobias** [comment]
Thanks!

I don't see `com.github.applied-science` or `io.github.applied-science` as groups. 

If you are trying to verify the `applied-science` or `appliedscience` groups, they aren't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under these groups, but won't be able to publish any new projects under them. You will need to use a domain-based group for that. 

Do you want me to go ahead and verify the `com|io.github.applied-science` groups?

**Comment by jackrusher** [comment]
No, thank you. I guess we'll have to make a new reverse DNS-based group, migrate all our old projects to the new group, then try to inform our tens of thousands of library users that the old coordinates are dead. 👍🏻

**Comment by tobias** [comment]
To be clear: you don't have to migrate _existing_ projects; [you can continue to deploy new versions of them](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-does-this-impact-existing-libraries-published-to-clojars). You only need a verified group for _new_ projects, so no migration to new coordinates is necessary.

**Comment by jackrusher** [comment]
To be clear: confusing users as to which is our actual group-id is not improving their security. So, [like the Lambda Island team](https://github.com/lambdaisland/open-source/issues/2) and other popular library makers, we will eventually move everything to a new unified group-id. Meanwhile, I'll be using git coordinates for any new libraries until I have the bandwidth to deal with this...

It would have been better, if less tidy, to grandfather in orgs that were already publishing libraries. 🤷🏻‍♂️
