### ISSUE TITLE
Requesting manual verification for group dev.gethop

### ISSUE THREAD

**Issue by lucassousaf** [clojars/administration#247]
I am requesting verification of a new group. The group name is: dev.gethop

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars gethop-dev`

**Comment by tobias** [comment]
The group https://clojars.org/groups/dev.gethop has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
