### ISSUE TITLE
New Group Creation and Verification: lt.jocas

### ISSUE THREAD

**Issue by dainiusjocas** [clojars/administration#248]
I am requesting verification of a [new | existing] group. The group name is: lt.jocas

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

```
$ dig txt jocas.lt


; <<>> DiG 9.10.6 <<>> txt jocas.lt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53623
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;jocas.lt.			IN	TXT

;; ANSWER SECTION:
jocas.lt.		900	IN	TXT	"v=spf1 a mx ptr redirect=spf.serveriai.lt"
jocas.lt.		900	IN	TXT	"clojars dainiusjocas"

;; Query time: 28 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue May 03 19:24:06 EEST 2022
;; MSG SIZE  rcvd: 124
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/lt.jocas has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
