### ISSUE TITLE
New Group Creation and Verification: com.thheller

### ISSUE THREAD

**Issue by thheller** [clojars/administration#249]
I am requesting verification of a new group. The group name is: com.thheller

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars thheller`

```
$ dig -t txt thheller.com

; <<>> DiG 9.16.22-Debian <<>> -t txt thheller.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14425
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;thheller.com.                  IN      TXT

;; ANSWER SECTION:
thheller.com.           1799    IN      TXT     "clojars thheller"

;; AUTHORITY SECTION:
thheller.com.           1800    IN      NS      dns1.registrar-servers.com.
thheller.com.           1800    IN      NS      dns2.registrar-servers.com.

;; Query time: 52 msec
;; SERVER: 213.133.99.99#53(213.133.99.99)
;; WHEN: Tue May 03 16:46:29 CEST 2022
;; MSG SIZE  rcvd: 126
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.thheller has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by thheller** [comment]
Thanks.
