### ISSUE TITLE
com.github.strojure

### ISSUE THREAD

**Issue by serioga** [clojars/administration#251]
I am requesting verification of a new group. The group name is: com.github.strojure

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.com` / `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-serioga`, and provided a link to that repository https://github.com/strojure/clojars-serioga

**Comment by tobias** [comment]
The groups com.github.strojure & io.github.strojure have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
