### ISSUE TITLE
Verification request for new group net.eighttrigrams

### ISSUE THREAD

**Issue by eighttrigrams** [clojars/administration#252]
Hello there,

My clojars username is `eighttrigrams`

I am requesting verification of a new group. The group name is: `net.eighttrigrams`

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars eighttrigrams`

Thanks and kind regards

**Comment by tobias** [comment]
The group https://clojars.org/groups/net.eighttrigrams has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by eighttrigrams** [comment]
Thanks!
