### ISSUE TITLE
Requesting group io.github.manetu

### ISSUE THREAD

**Issue by ghaskins** [clojars/administration#253]
I am requesting verification of a [new | existing] group. The group name is: io.github.manetu

- [ ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.com` / `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

https://github.com/manetu/clojars-ghaskins

**Comment by tobias** [comment]
The groups com.github.manetu & io.github.manetu have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
