### ISSUE TITLE
Verify com.flipkart group

### ISSUE THREAD

**Issue by regunathb** [clojars/administration#259]
I am requesting verification of an existing group. The group name is: com.flipkart

- I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (https://github.com/flipkart)
- I have created a public repository under that group named `clojars-flipkartoss`, and provided a link to that repository : https://github.com/Flipkart/clojars-flipkartoss

**Comment by tobias** [comment]
Hi @regunathb!

You can only verify a github-based groupname (so `com.github.flipkart` / `io.github.flipkart`) using the GitHub repository method. If you want to verify `com.flipkart`, you will need to add a TXT DNS record to `flipkart.com` with the value `clojars flipkartoss`. Please see the details in [the FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-do-i-verify-a-group-name).

**Comment by regunathb** [comment]
Thanks Tobias for the quick response. I had a follow up question : we have projects such as flux, grpc-jexpress that would eventually be published as the artifactIds for these projects. I presume the group Id for which I need to add the TXT DNS would be only for the group i.e. com.flipkart?

**Comment by tobias** [comment]
If the projects are released under the `com.flipkart` group (i.e. `com.flipkart/flux`, `com.flipkart/grpc-jexpress`), then you would only need to verify the `com.flipkart` group itself, once. Then you can deploy any projects to that group in the future.

**Comment by regunathb** [comment]
Thank you. This clarifies. Will try the above and get back to this ticket for verification to proceed.

**Comment by regunathb** [comment]
The TXT DNS record has been added to flipkart.com with the value as clojars flipkartoss. Can you please check and complete the group verification?

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.flipkart has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
