### ISSUE TITLE
Verify com.wsscode

### ISSUE THREAD

**Issue by wilkerlucio** [clojars/administration#26]
I am requesting verification of a existing group. The group name is: `com.wsscode`

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars wilkerlucio`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/com.wsscode has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
