### ISSUE TITLE
Verify sub-domain groups of com.flipkart

### ISSUE THREAD

**Issue by regunathb** [clojars/administration#263]
I am requesting verification of sub-domain groups of an already verified group. The group name is: com.flipkart

- [] I have read the FAQ on sub-domain group verification here : https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-do-i-verify-a-group-name

Can you please verify the following sub-domain groups:
- com.flipkart.flux
- com.flipkart.grpc-jexpress

**Comment by tobias** [comment]
The groups https://clojars.org/groups/com.flipkart.flux and https://clojars.org/groups/com.flipkart.grpc-jexpress have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in.
