### ISSUE TITLE
Request for new group: no.cjohansen

### ISSUE THREAD

**Issue by cjohansen** [clojars/administration#264]
I am requesting verification of a new group. The group name is: no.cjohansen

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

```
dig +noall +answer TXT cjohansen.no
cjohansen.no.		300	IN	TXT	"clojars cjohansen"
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/no.cjohansen has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by cjohansen** [comment]
Thanks 👍
