### ISSUE TITLE
The new group ai.z7 creation request

### ISSUE THREAD

**Issue by source-c** [clojars/administration#267]
I am requesting verification of a new group. The group name is: ai.z7

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars source-c`

**Comment by tobias** [comment]
The group https://clojars.org/groups/ai.z7 has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by source-c** [comment]
Thank you very much.
