### ISSUE TITLE
flybot-sg

### ISSUE THREAD

**Issue by robertluo** [clojars/administration#268]
I am requesting verification of a existing group. The group name is: flybot. The domain name is flybot.sg

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a reverse-domain-based group(https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>` (domain clojars.flybot.sg, value renewdoit)

Or:

- [ ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.com` / `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

**Comment by tobias** [comment]
The group `flybot` isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. 

The TXT record on the `flybot.sg` domain can be used to verify the group `sg.flybot` -- would you like to verify that group?

**Comment by tobias** [comment]
The group https://clojars.org/groups/sg.flybot has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
