### ISSUE TITLE
New group: com.pitch

### ISSUE THREAD

**Issue by adamrenklint** [clojars/administration#269]
I am requesting verification of a new group. The group name is: com.pitch

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars adamrenklint`

**Comment by tobias** [comment]
Hi @adamrenklint! 

I looked for the appropriate TXT record on pitch.com, but I'm not seeing it. Also, note that the TXT record needs to point to an existing Clojars _user_ name, not to the group being verified (unless they are the same). I don't see a user called `com.pitch`.

**Comment by adamrenklint** [comment]
Sorry about that, have changed it to point to my username now.

**Comment by tobias** [comment]
Thanks @adamrenklint. I'm still not seeing the clojars TXT record:

```
$ dig txt +short pitch.com
"apple-domain-verification=FgM2OhHIZDNnU0FB"
"notion_verify_wGWaDUeAMf4]]9>XrzmW#*Zu=D@K?p,kLwDre0.7oGF:,X67WVo0jDh}:Ziap#8Cnk3>XX"
"google-site-verification=Sz1kpWaj7dI-0z9axNyFfkRYd0KyTK2fRHZTERimnoE"
"google-site-verification=pKnEiDSu2U61eiMK9s4a0TztDQJ7xe2lrWyndkeJIUk"
"google-site-verification=EvrVASLZdR5fs_OnJSafT9Z3rZ7R8PWiKlNWp4X1NNs"
"google-site-verification=GtbDtY_2Itfq7f_qIja3jOCv-Z3I0BqBtJeIRHmk2iw"
"v=spf1 a mx include:_spf.google.com include:amazonses.com include:servers.mcsv.net -all"
"google-site-verification=FL964mrau27D7YOZYzGOeH8WTME7KMZCdBt_3N2Npw8"
```

**Comment by adamrenklint** [comment]
Ok, pretty sure it should work now.

```
$ dig txt +short pitch.com
"notion_verify_wGWaDUeAMf4]]9>XrzmW#*Zu=D@K?p,kLwDre0.7oGF:,X67WVo0jDh}:Ziap#8Cnk3>XX"
"google-site-verification=FL964mrau27D7YOZYzGOeH8WTME7KMZCdBt_3N2Npw8"
"apple-domain-verification=FgM2OhHIZDNnU0FB"
"google-site-verification=Sz1kpWaj7dI-0z9axNyFfkRYd0KyTK2fRHZTERimnoE"
"google-site-verification=pKnEiDSu2U61eiMK9s4a0TztDQJ7xe2lrWyndkeJIUk"
"google-site-verification=EvrVASLZdR5fs_OnJSafT9Z3rZ7R8PWiKlNWp4X1NNs"
"google-site-verification=GtbDtY_2Itfq7f_qIja3jOCv-Z3I0BqBtJeIRHmk2iw"
"v=spf1 a mx include:_spf.google.com include:amazonses.com include:servers.mcsv.net -all"
"clojars adamrenklint"
```

**Comment by tobias** [comment]
Yep, I see it now. Thanks!

The group https://clojars.org/groups/com.pitch has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
