### ISSUE TITLE
New Group Creation: me.mourjo

### ISSUE THREAD

**Issue by mourjo** [clojars/administration#270]
I am requesting verification of a new group. The group name is: me.mourjo

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars mourjo`

**Comment by tobias** [comment]
The group https://clojars.org/groups/me.mourjo has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
