### ISSUE TITLE
New group name creation

### ISSUE THREAD

**Issue by ashwinbhaskar** [clojars/administration#273]
I am requesting verification of a new group. The group name is:`io.github.ashwinbhaskar`

- [ ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.com` / `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

**Comment by ashwinbhaskar** [comment]
hi @tobias yes, that worked. I am able to login with github and the dashboard shows `io.github.ashwinbhaskar` as a verified group. Is that it?

**Comment by tobias** [comment]
Yep, you should be all set @ashwinbhaskar!
