### ISSUE TITLE
dfbernal verification

### ISSUE THREAD

**Issue by dfbernal** [clojars/administration#276]
I am requesting verification of a [new | existing] group. The group name is: <dfbernal>

- [ ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Or:

- [x ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x ] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.com` / `io.github.foo`)
- [x ] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

https://github.com/dfbernal/clojars-kueso

**Comment by tobias** [comment]
Hi @dfbernal! If you are trying to verify `com.github.dfbernal` and `io.github.dfbernal`, note that you can verify them automatically by logging in to Clojars using the "Log in with GitHub" option: 

![image](https://user-images.githubusercontent.com/2631/179210704-d94b658a-f017-4d25-9f30-3f3b704913dc.png)

As long as the email address associated with your Clojars account is one of the verified emails on your GitHub account, you will be logged in and those groups will be verified. Your usernames don't need to match.

If that doesn't work for you, let me know and I'll verify the groups manually.

**Comment by tobias** [comment]
It looks like this worked, closing.
