### ISSUE TITLE
verifying existing byu-odh

### ISSUE THREAD

**Issue by WorldsEndless** [clojars/administration#279]
- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.foo` / `io.github.foo`)
- [X] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository
  
clojars-worldsendless 
https://gitlab.com/BYU-ODH/clojars-worldsendless

The clojars is lowercase, while the gitlab is uppercase:

byu-odh -> BYU-ODH

**Comment by tobias** [comment]
The group `byu-odh` isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. 

If you don't have a domain to use for the group, there are several other options available - please see the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#do-i-have-to-have-my-own-domain-name-to-publish-to-clojars). 

The verification repo gives you access to the `com.gitlab.byu-odh` and `io.gitlab.byu-odh` groups. Would you like to verify those?

**Comment by WorldsEndless** [comment]
The goal is to resume publication to my byu-odh group where I already have libraries. To this end I have gone through the gitlab steps. The problem is that the cases don't match although both are well-used: on Clojars, it's byu-odh , while on GitLab it's BYU-ODH.

Is this the problem with my gitlab verification? If they are made matching case will that solve the problem? Is an exception possible, so I don't risk breaking library-users and CI/CD processes with a name change?

- Tory

**Comment by tobias** [comment]
The issue here is that `byu-odh` isn't domain-based, so can't be verified under the [Verified Group Names policy](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names). So you won't be able to publish any _new_ libraries to that group. Note that you can continue to release new versions of _existing_ libraries under that group, so no existing libraries need a new name. This should avoid breaking existing usage and CI/CD processes.

**Comment by tobias** [comment]
I'm closing this since you've verified `edu.byu.odh`, but feel free to reopen if you want to verify the gitlab-based groups as well.
