### ISSUE TITLE
Please verify org.msync

### ISSUE THREAD

**Issue by jaju** [clojars/administration#28]
I am requesting verification of an existing group. The group name is: 

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Thank you!

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/org.msync has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by jaju** [comment]
Thank you! 🙏
