### ISSUE TITLE
Verify sub-domain group of com.flipkart

### ISSUE THREAD

**Issue by regunathb** [clojars/administration#282]
I am requesting verification of sub-domain group of an already verified group. The group name is: com.flipkart

[] I have read the FAQ on sub-domain group verification here : https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-do-i-verify-a-group-name
Can you please verify the following sub-domain group:

com.flipkart.dkv

We need this for releasing client libraries for our Distributed KV store OSS project : https://github.com/flipkart-incubator/dkv

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.flipkart.dkv has been verified and the `flipkartoss` user added as the first member.

**Comment by regunathb** [comment]
Thank you @tobias
