### ISSUE TITLE
Verification requests for com.tcgplayer

### ISSUE THREAD

**Issue by dfbernal** [clojars/administration#289]
I am requesting verification of a [new | existing] group. The group name is: <group name here>

- [ ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>` on the domain `<domain>`

Or:

- [ x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.foo` / `io.github.foo`)
- [ x] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

**Comment by dfbernal** [comment]
https://github.com/TCGplayer/clojars-tcg_dbernal

**Comment by tobias** [comment]
Hi @dfbernal! 

Providing a verification repo will verify github-based groups (`com.github.tcgplayer` / `io.github.tcgplayer`), but not `com.tcgplayer`, since the repository can't demonstrate ownership of the `tcgplayer.com` domain. To verify `com.tcgplayer`, you will have to add a TXT record to `tcgplayer.com`.

**Comment by tobias** [comment]
Hi @dfbernal, I'm checking back in to see what you want to do here. Do you want to verify the github-based domains?

**Comment by dfbernal** [comment]
Hi @tobias, we have added the TXT record to the domain. Could you please verify it?

**Comment by tobias** [comment]
Hi @dfbernal! I hate to ask you to do more work here, but the txt record needs to include your _Clojars_ username, not your GitHub username. We use that value to assign the first administrative user to the group so you can manage and deploy to it. 

Can you update the TXT record to point to your Clojars username?

**Comment by dfbernal** [comment]
@tobias Ok, I updated the record.

```
; <<>> DiG 9.10.6 <<>> tcgplayer.com txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48680
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;tcgplayer.com.			IN	TXT

;; ANSWER SECTION:
tcgplayer.com.		86400	IN	TXT	"MS=ms55467768"
tcgplayer.com.		86400	IN	TXT	"clojars tcg_dbernal"
tcgplayer.com.		86400	IN	TXT	"apple-domain-verification=A1tBNwp719rBrU57"
tcgplayer.com.		86400	IN	TXT	"google-site-verification=6dF5NSS8GF3wbI6JTyppuXKc7XQhSwY_gd7HMJjyOHc"
tcgplayer.com.		86400	IN	TXT	"v=spf1 include:_spf.google.com include:sendgrid.net include:mail.zendesk.com -all"
tcgplayer.com.		86400	IN	TXT	"google-site-verification=KqeRugK39fvYReyIWNehim_bo55bfzWt_sd_913IyNQ"

;; Query time: 97 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Tue Aug 30 10:54:52 EDT 2022
;; MSG SIZE  rcvd: 411
```
