### ISSUE TITLE
Verification request for space.matterandvoid

### ISSUE THREAD

**Issue by dvingo** [clojars/administration#29]
I am requesting verification of a [new | existing] group. The group name is: 

- [x] This group is space.matterandvoid
- [x] I have added a TXT DNS record for the domain that has a value of `clojars dvingo`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/space.matterandvoid has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
