### ISSUE TITLE
Verify je.suis

### ISSUE THREAD

**Issue by xorgy** [clojars/administration#294]
I am requesting verification of an existing group. The group name is: je.suis

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>` on the domain `<domain>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/je.suis has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
