### ISSUE TITLE
Verification Request for "io.github.alchemiakr" group

### ISSUE THREAD

**Issue by ajchemist** [clojars/administration#295]
I am requesting verification of a [new | existing] group. The group name is: `io.github.alchemiakr`

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.foo` / `io.github.foo`)
- [X] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository <https://github.com/alchemiakr/clojars-ajchemist>

**Comment by tobias** [comment]
The groups com.github.alchemiakr & io.github.alchemiakr have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
