### ISSUE TITLE
The new group com.dkdhub creation request

### ISSUE THREAD

**Issue by source-c** [clojars/administration#299]
I am requesting verification of a new group. The group name is: com.dkdhub

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars source-c` on the domain `dkdhub.com`

**Comment by danielcompton** [comment]
Hey, I've done this now, sorry for the delay.

**Comment by source-c** [comment]
Thank you!
