### ISSUE TITLE
New group verification: net.r4s6

### ISSUE THREAD

**Issue by rwstauner** [clojars/administration#3]
I am requesting verification of a new group. The group name is: `net.r4s6`

**Comment by tobias** [comment]
Hi @rwstauner! You'll be the first verification, so please bear with me as we figure this out.

Would it be possible for you to create a `TXT` record for the `r4s6.net` domain that contains: `clojars-3 <your-clojars-username>`? Let me know when that is up and I'll confirm.

Thanks!

**Comment by rwstauner** [comment]
done, thank you!

**Comment by tobias** [comment]
Thanks! `net.r4s6` is now verified. There's not yet a way to see that in the UI, but I plan to implement a "verified" badge soon.
