### ISSUE TITLE
Existing clojars group verification for com.phronemophobic

### ISSUE THREAD

**Issue by phronmophobic** [clojars/administration#30]
I am requesting verification of an existing group. The group name is: com.phronemophobic

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars phronmophobic`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/com.phronemophobic has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by phronmophobic** [comment]
Thank you!
