### ISSUE TITLE
Group verification com.ardoq

### ISSUE THREAD

**Issue by holyjak** [clojars/administration#300]
I am requesting verification of a existing group. The group name is: com.ardoq

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars holyjak` on the domain `com.ardoq`

Thank you!

**Comment by danielcompton** [comment]
Hey, I've added this now. Thanks!

**Comment by holyjak** [comment]
Thx a lot, Daniel!
