### ISSUE TITLE
Create and verify a new group: io.epiccastle

### ISSUE THREAD

**Issue by retrogradeorbit** [clojars/administration#301]
I am requesting verification of a new group. The group name is: io.epiccastle

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars retrogradeorbit` on the domain `epiccastle.io`

**Comment by danielcompton** [comment]
The group https://clojars.org/groups/epiccastle.io has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT records if you like.

**Comment by retrogradeorbit** [comment]
thankyou!
