### ISSUE TITLE
Group verification request for io.zalky

### ISSUE THREAD

**Issue by zalky** [clojars/administration#302]
I am requesting verification of a new group. The group name is: io.zalky

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars zalky` on the domain `zalky.io`

**Comment by danielcompton** [comment]
The group https://clojars.org/groups/io.zalky has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT records if you like.
