### ISSUE TITLE
Group verification request for io.factorhouse

### ISSUE THREAD

**Issue by d-t-w** [clojars/administration#303]
I am requesting verification of a new group. The group name is: io.factorhouse

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars d-t-w` on the domain `factorhouse.io`

**Comment by danielcompton** [comment]
Hey Derek, sorry for the delay, I've verified this now.

**Comment by d-t-w** [comment]
Thanks Dan!
