### ISSUE TITLE
new group creation for party.donut

### ISSUE THREAD

**Issue by flyingmachine** [clojars/administration#304]
I am requesting verification of a new group. The group name is: party.donut

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>` on the domain `<domain>`

**Comment by danielcompton** [comment]
Hey Daniel, this is verified now. You can remove the TXT record if you'd like.
