### ISSUE TITLE
Group verification for io.github.parencat/fx project

### ISSUE THREAD

**Issue by margintop15px** [clojars/administration#305]
I am requesting verification of a new group. The group name is: io.github.parencat

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (https://github.com/parencat)
- [x] I have created a public repository under that group named `clojars-tka4enko`, and provided a link to that repository https://github.com/parencat/clojars-tka4enko

**Comment by danielcompton** [comment]
The groups com.github.parencat & io.github.parencat have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
