### ISSUE TITLE
Delete org.clojars.likid_geimfari/secrets

### ISSUE THREAD

**Issue by lk-geimfari** [clojars/administration#309]
I am requesting deletion of my JAR because:

- [ ] There is a security vulnerability in a published JAR, i.e. malicious code
- [x] Private credentials or code have been published.

If you are not requesting deletion for either of those reasons, we will not delete your artifact.

Artifact URL: https://clojars.org/org.clojars.likid_geimfari/secrets

**Comment by tobias** [comment]
This jar has been deleted. Note that you should consider any credentials that were in that jar as compromised, since they were publicly available.
