### ISSUE TITLE
Group verification of io.github.futjure

### ISSUE THREAD

**Issue by frenchy64** [clojars/administration#311]
I am requesting verification of a new group. The group name is: io.github.futjure

https://github.com/futjure/clojars-frenchy64

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.foo` / `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

**Comment by tobias** [comment]
The groups com.github.futjure & io.github.futjure have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
