### ISSUE TITLE
Group verification of is.d0x

### ISSUE THREAD

**Issue by madvas** [clojars/administration#313]
I am requesting verification of a new group. The group name is: `is.d0x`

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars madvas` on the domain `is.d0x`

```
nslookup -type=txt d0x.is
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
d0x.is	text = "clojars madvas"
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/is.d0x has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
