### ISSUE TITLE
Verification for io.github.clj-kondo

### ISSUE THREAD

**Issue by borkdude** [clojars/administration#314]
I am requesting verification of a [new | existing] group. The group name is: <group name here>

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.foo` / `io.github.foo`)
- [x] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

Group:

io.github.clj-kondo

Repo:

https://github.com/clj-kondo/clojars-borkdude

**Comment by tobias** [comment]
The groups com.github.clj-kondo & io.github.clj-kondo have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
