### ISSUE TITLE
New group: io.jepsen

### ISSUE THREAD

**Issue by aphyr** [clojars/administration#315]
I am requesting verification of a newgroup. The group name is: io.jepsen

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars aphyr@aphyr.com` on the domain `jepsen.io`

Thank you!

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.jepsen has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by aphyr** [comment]
Thank you!
