### ISSUE TITLE
New Group Creation

### ISSUE THREAD

**Issue by tapochqa** [clojars/administration#317]
I am requesting verification of a new group. The group name is: link.lmnd

- [🍆] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [🍆] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [🍆] I have added a TXT DNS record for the domain that has a value of `clojars tapochqa` on the domain `lmnd.link`

**Comment by tobias** [comment]
The group https://clojars.org/groups/link.lmnd has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
