### ISSUE TITLE
Verify com.kiranshila

### ISSUE THREAD

**Issue by kiranshila** [clojars/administration#32]
I am requesting verification of a new group. The group name is: `com.kiranshila`

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars kiranshila`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/com.kiranshila has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
