### ISSUE TITLE
Requesting verification of new group: borge.by

### ISSUE THREAD

**Issue by anderseknert** [clojars/administration#320]
I am requesting verification of a new group. The group name is: borge.by

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars anderseknert` on the domain `borge.by`

**Comment by tobias** [comment]
You had requested to verify the group `borge.by`, but groups are _reverse_ domains, so I verified `by.borge`.

The group https://clojars.org/groups/by.borge has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by anderseknert** [comment]
Oh, that makes sense! Thanks @tobias 👍
