### ISSUE TITLE
verify group "com.oakmac"

### ISSUE THREAD

**Issue by oakmac** [clojars/administration#326]
I am requesting verification of an existing group. The group name is: `com.oakmac`

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars oakmac` on the domain `oakmac.com`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.oakmac has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
