### ISSUE TITLE
New Group Name: design.kushi

### ISSUE THREAD

**Issue by paintparty** [clojars/administration#328]
I am requesting verification of a new group. The group name is: design.kushi

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars paintparty` on the domain `kushi.design`

Or:

- [ ] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.foo` / `io.github.foo`)
- [ ] I have created a public repository under that group named `clojars-<your clojars username>`, and provided a link to that repository

**Comment by tobias** [comment]
The group https://clojars.org/groups/design.kushi has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

**Comment by paintparty** [comment]
Thank you!
