### ISSUE TITLE
Please create a sub-domain-based group 'com.flipkart.krystal'

### ISSUE THREAD

**Issue by RamAnvesh** [clojars/administration#332]
I am requesting verification of a new sub-domain-based group under an existing verified group. 
The new group name is: com.flipkart.krystal
The existing group name is: com.flipkart

- [✓] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [✓] This group is a [sub-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)

Ref:
Other sub-domain-based groups were verified in the past here: https://github.com/clojars/administration/issues/274

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.flipkart.krystal has been created & verified under the `flipkartoss` acccount.

**Comment by RamAnvesh** [comment]
Thanks a ton for the quick response!
