### ISSUE TITLE
Verify existing group 'pieterbreed'. This is both my github, gitlab and clojars usernames.

### ISSUE THREAD

**Issue by pieterbreed** [clojars/administration#333]
- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/pieterbred -> `com.github.pieterbreed` / `io.github.pieterbreed`)
- [X] I have created a public repository under that group named `clojars-pieterbreed`, and provided a link to that repository

https://gitlab.com/pieterbreed/clojars-pieterbreed

**Comment by tobias** [comment]
The group `pieterbreed` isn't domain-based, so can't be verified. You can continue to push versions of _existing_ projects under this group, but won't be able to publish any new projects under it. You will need to use a domain-based group for that. 

You can verify _new_ groups based on your GitHub/Gitlab identities:
- `com.github.pieterbreed`
- `io.github.pieterbreed`
- `com.gitlab.pieterbreed`
- `io.gitlab.pieterbreed`

Logging in to Clojars via "Login with GitHub" or "Login with GitLab.com" will auto-verify those groups, respectively. We can also use the verification repository you have created to verify the `com|io.gitlab.pieterbreed` pair if you like.

**Comment by pieterbreed** [comment]
In that case, kindly verify *com.gitlab.pieterbreed* for me.

Regards,
Pieter

**Comment by tobias** [comment]
The groups com.gitlab.pieterbreed & io.gitlab.pieterbreed have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.
