### ISSUE TITLE
Please verify com.primeteach group name

### ISSUE THREAD

**Issue by primeteach-developers** [clojars/administration#334]
Dear Clojars

I am requesting verification of a new group. The group name is: com.primeteach

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>` on the domain `<domain>`

Kind Regards

David Schmitter <david.schmitter@primeteach.com>

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.primeteach has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.
