### ISSUE TITLE
Create group com.github.kalai-transpiler

### ISSUE THREAD

**Issue by echeran** [clojars/administration#335]
Requested group name: `com.github.kalai-transpiler`

- [X] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization (ex: https://github.com/foo -> `com.github.foo` / `io.github.foo`)
- [X] I have created a public repository under that group named [`clojars-echeran`](https://github.com/kalai-transpiler/clojars-echeran), and provided a link to that repository

cc: @timothypratley

**Comment by tobias** [comment]
Hi @echeran (and @timothypratley)! 

Verification is now self-service (we released it earlier this week), so you can now verify your groups by visiting https://clojars.org/verify/group. Let me know if that doesn't work for you!

**Comment by echeran** [comment]
That worked, thanks!

**Comment by tobias** [comment]
Great, thanks for letting me know @echeran!

**Comment by timothypratley** [comment]
nice!!! :) 👍
