### ISSUE TITLE
Verify sub-domain group of com.flipkart

### ISSUE THREAD

**Issue by kingster** [clojars/administration#336]
I am requesting verification of sub-domain group of an already verified group. The group name is: com.flipkart

[] I have read the FAQ on sub-domain group verification here : https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#how-do-i-verify-a-group-name
Can you please verify the following sub-domain group:

com.flipkart.chronosq

We need this for releasing client libraries for our Distributed Scheduler OSS project : https://github.com/flipkart-incubator/chronosq

**Comment by tobias** [comment]
Hi @kingster! I saw that you tried to self-verify on clojars.org, but it failed. The error message is misleading, but the issue was you aren't a member of the `com.flipkart` group, only `flipkartoss` is. Can you log in to clojars.org as flipkartoss and try again?

**Comment by kingster** [comment]
Sure, Let me try this and see if I am able to verify the sub-domain by myself.

**Comment by kingster** [comment]
I was able to verify via `flipkartoss` account. Thanks for the tip :)
