### ISSUE TITLE
verify co.cljazz

### ISSUE THREAD

**Issue by avelino** [clojars/administration#337]
I'm requesting verification of a [new | existing] group. The group name is: `co.cljazz`

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars avelino`

Thanks for keeping Clojars safe and available for the Clojure community!

ref: https://github.com/cljazz/supabase-clj/issues/9

**Comment by tobias** [comment]
Hi @avelino! Thanks for the kind words.

Verification is now self-service; see https://clojars.org/verify/group. Let me know if that doesn't work for you!
