### ISSUE TITLE
adding Medidata.OpenSourceMaintainers@3ds.com to https://clojars.org/clojure-mauth-client

### ISSUE THREAD

**Issue by magnihotri-mdsol** [clojars/administration#339]
Hello,
We need to add Medidata.OpenSourceMaintainers@3ds.com as admin to repo https://clojars.org/clojure-mauth-client
please suggest the steps to achieve this.

best regards,
Murlidhar

**Comment by tobias** [comment]
Hi @magnihotri-mdsol! The group https://clojars.org/groups/clojure-mauth-client currently has one member:  https://clojars.org/users/pram0d. This user can log in and invite other users as members of the group. Is it possible to have pram0d do that?

**Comment by magnihotri-mdsol** [comment]
Hello @tobias
we are unable to connect with https://clojars.org/users/pram0d
The git repository referred is from Medidata public git repository and we need to add org email ID Medidata.OpenSourceMaintainers@3ds.com to the group, this would help in streamlined maintainability of the code.

**Comment by tobias** [comment]
That makes sense @magnihotri-mdsol. Here is what you will need to do:
- create a user account at clojars.org for that email address
- create a file in the https://github.com/mdsol/clojure-mauth-client repository called `clojars-verification` that contains the username of that user you created (you'll be able to delete this file when we are done)

I can then use that to confirm you own the repository, and add that username as an admin of the `clojure-mauth-client` group.

**Comment by magnihotri-mdsol** [comment]
added clojars-verification.txt with user name to be added as admin.
thank you

**Comment by tobias** [comment]
@magnihotri-mdsol can you provide a link to the file? I don't see it.

**Comment by tobias** [comment]
Oh, I see it on the branch. Working on adding it now.

**Comment by tobias** [comment]
`medidata_opensource` is now an admin member of https://clojars.org/groups/clojure-mauth-client. You can delete the verification file. 

Let me know if you have any issues!
