### ISSUE TITLE
Verify cc.qbits

### ISSUE THREAD

**Issue by mpenet** [clojars/administration#34]
I am requesting verification of a existing group. The group name is: cc.qbits

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>` https://dns.google.com/query?name=*.qbits.cc&rr_type=TXT&ecs=&disable_dnssec=true&show_dnssec=true

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/cc.qbits has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by mpenet** [comment]
thanks
