### ISSUE TITLE
Please transfer metrics-clojure credentials to ieugen / clj-commons

### ISSUE THREAD

**Issue by ieugen** [clojars/administration#340]
Hello,

Can I please get the clojars metrics-clojure project transfered to me or clj-commons? 
The project was transferred to clj-commons and would like to publish the new release.

https://github.com/clj-commons/metrics-clojure/issues/146
https://github.com/clj-commons/metrics-clojure

cc @michaelklishin  , @sjl

**Comment by tobias** [comment]
@michaelklishin Would you be willing to add @ieugen as an admin to the metrics-clojure groups on Clojars? 

@ieugen can you share your Clojars username here for Michael to use? Once you have admin rights to the groups, you'll have the same rights as Michael and it will effectively be transferred.

I see all of the following groups for reference:

[metrics-clojure](https://clojars.org/groups/metrics-clojure)
[metrics-clojure-ganglia](https://clojars.org/groups/metrics-clojure-ganglia)
[metrics-clojure-graphite](https://clojars.org/groups/metrics-clojure-graphite)
[metrics-clojure-health](https://clojars.org/groups/metrics-clojure-health)
[metrics-clojure-influxdb](https://clojars.org/groups/metrics-clojure-influxdb)
[metrics-clojure-jvm](https://clojars.org/groups/metrics-clojure-jvm)
[metrics-clojure-riemann](https://clojars.org/groups/metrics-clojure-riemann)
[metrics-clojure-ring](https://clojars.org/groups/metrics-clojure-ring)

**Comment by michaelklishin** [comment]
@tobias I will if you tell me how that's done. I could not quickly find any relevant Leiningen or Clojars docs.

**Comment by ieugen** [comment]
hi @tobias : I am ieugen on Clojars . https://clojars.org/io.github.ieugen/calcite-clj . (I only saw the name in Dashboard page - not on profile ). 

@michaelklishin : do you want to remain admin / involved after the transfer ?

**Comment by tobias** [comment]
Thanks @ieugen.

@michaelklishin Sure thing! 

1. Log in to clojars.org
2. On the Dashboard page, click on the group you want to update: 
   
![image](https://github.com/clojars/administration/assets/2631/4ac8d690-8f80-46ac-bc1e-7e368c120f52)

3. Under "Add permission to group", enter the username, then check "Admin?":

![image](https://github.com/clojars/administration/assets/2631/ca394923-8102-4504-842a-907410ed737d)

4. Press "Add Permission"

You'll have to do that for each group you want to share.

**Comment by michaelklishin** [comment]
> @michaelklishin : do you want to remain admin / involved after the transfer ?

Good question. Given my track record of contributions to OSS Clojure projects in the last 7-8 years, I really should not :)

**Comment by michaelklishin** [comment]
It turns out, I am not an administrator in that Clojars repo, only @sjl is :(

**Comment by sjl** [comment]
I've added @ieugen as an admin to the `metrics-clojure` and `metrics-clojure-ring` groups on Clojars.  Those are the only two groups I have access to -- I don't know who's in charge of the other `metrics-clojure-*` groups.

**Comment by ieugen** [comment]
Thanks @sjl . 
Do you still want to be admin on the repos? 

I noticed that the artifact-id is doubled as group-id for a metrics-clojure projects.

@tobias : Could this have been done automatic during the mandate of group ids in clojars?
I think we will have to rely on you/someone from clojars.

**Comment by tobias** [comment]
Thanks @slj! 

@ieugen: I saw the other `metrics-clojure-*` listed as groups that @michaelklishin was a member of here: https://clojars.org/users/michaelklishin, so assumed they were part of metrics-clojure in some way. They were not automatically created by Clojars. They match subprojects listed in https://github.com/clj-commons/metrics-clojure, so I believe they were created by deploying those subprojects. 

@michaelklishin was the admin of the following groups (maybe they were created after the other two groups), but I went ahead and added "ieugen" as an admin for them. You should be all set @ieugen! 

- [metrics-clojure-ganglia](https://clojars.org/groups/metrics-clojure-ganglia)
- [metrics-clojure-graphite](https://clojars.org/groups/metrics-clojure-graphite)
- [metrics-clojure-health](https://clojars.org/groups/metrics-clojure-health)
- [metrics-clojure-influxdb](https://clojars.org/groups/metrics-clojure-influxdb)
- [metrics-clojure-jvm](https://clojars.org/groups/metrics-clojure-jvm)
- [metrics-clojure-riemann](https://clojars.org/groups/metrics-clojure-riemann)

**Comment by ieugen** [comment]
Thank you @tobias . 

Thanks @sjl and @michaelklishin  for your support. 

One final question before I close this. 
One of my thoughts is to reduce the number of groups / artifacts - to reduce the burden on maintenance.

Does clojars have support for artifact redirection / deprecation notice?
Something that could help people know these artifacts will no longer be released and maybe redirect them to options ?

**Comment by tobias** [comment]
@ieugen We don't have any sort of automated redirection or deprecation notices. Folks generally put "DEPRECATED, use foo/bar" as the description on a final release, but Clojars does not do anything special with it.

The primary issue with redirection is there is no way for tooling (lein, tools.deps, maven) from knowing that the redirection should happen, which can result in conflicting versions on the classpath, since the tooling can't know that `foo/foo` and `bar/foo` are the same project, so will include both.

Because of that, the current recommendation is to _not_ regroup/rename projects unless you have to. There is a lot of detail in [this discussion](https://github.com/clojars/clojars-web/discussions/870) as to why.

**Comment by tobias** [comment]
I'm closing this as done.
