### ISSUE TITLE
Upload size exception for https://clojars.org/io.github.pfeodrippe/vybe

### ISSUE THREAD

**Issue by pfeodrippe** [clojars/administration#342]
Hi,

Could I have an upload size exception for https://clojars.org/io.github.pfeodrippe/vybe, around 60MB (for future proof)? (Convo started at  https://clojurians.slack.com/archives/C0H28NMAS/p1729468760562019?thread_ts=1729185583.586609&channel=C0H28NMAS&message_ts=1729468760.562019).

https://github.com/pfeodrippe/vybe is a game framework that leverages the Panama project for being able to some C libs (for graphics, physics, audio (using overtone, but it has to have the SC native libs)), we have it set up for 3 distinct platforms right now (macOS, windows and Linux), each one of them leading to a different dep, so we may be able to optimize things for a platform to reduce the size as we add new libs.

Appreciate the work you do here, clojars just… works!!! 

Thanks

**Comment by tobias** [comment]
Override added via https://github.com/clojars/infrastructure/pull/49 and https://github.com/clojars/infrastructure/pull/50.
