### ISSUE TITLE
deletion request: different project pushed to no.cjohansen/replicant by mistake

### ISSUE THREAD

**Issue by gaverhae** [clojars/administration#343]
I am requesting deletion of this JAR because:

- ~[ ] There is a security vulnerability in a published JAR, i.e. malicious code~
- [?] Private credentials or code have been published.

If you are not requesting deletion for either of those reasons, we will not delete your artifact.

Artifact URL: https://clojars.org/no.cjohansen/replicant/versions/2024.09.29

---

## Disclaimer

I am not the maintainer for this project. The project belongs to @cjohansen. I'm just a user trying to improve the user experience for it.

## Case for deletion

While this artifact does not technically contain _private_ code, it does contain — exclusively — code from a different project. As such, I posit that:
- It is highly unlikely anyone is willingly depending on this specific version of the project, as it is in fact [a different project](https://github.com/cjohansen/lookup). It does not contain the expected namespaces and thus does not work at all for any project expecting to use [replicant].
- This is in the spirit of Valid Reason 2, in that the code contained in this version is not code intended for this artifact.

The existence of this artifact is an issue mainly because [lookup] uses a different version scheme, making this broken, non-[replicant] version of the [replicant] artifact appear as the newest version of [replicant] to automated tools such as `lein ancient`.

[lookup]: https://github.com/cjohansen/lookup
[replicant]: https://github.com/cjohansen/replicant

## Concessions

I believe the fact that the [lookup] code that has been wrongly uploaded happens to be separately open-source should not prevent it from being considered "private" in this context, but could see the opposite argument.

It could be argued that the most egregious problem here lies with external tooling, i.e. the fact that `lein ancient` orders the broken version above working, more recent ones, and that that could be fixed by @cjohansen through pushing a new version scheme for [replicant].

I could understand the Clojars maintainers taking the position that this is not worth fixing, as there is an easy (though likely distatesful to @cjohansen as he may not be ready to drop the foreboding `0.` from [replicant] version strings) workaround and not that much of a cost in keeping a bad artifact around after that point, but thought it was worth asking.

**Comment by cjohansen** [comment]
Thank you for this writeup @gaverhae 

I just wanted to confirm that this version is indeed a mistake.

**Comment by tobias** [comment]
Thanks for the well thought out case @gaverhae! I'm a bit covered up with work today, and will be away from the computer this evening until Tuesday, but I will give it some thought and get back to y'all next week.

**Comment by tobias** [comment]
I agree that it makes sense to delete this erroneous version, since it isn't replicant at all. I have removed the offending version.

**Comment by cjohansen** [comment]
Thanks @tobias 🙌

**Comment by gaverhae** [comment]
Thank you @tobias !

**Comment by tobias** [comment]
My pleasure!
