### ISSUE TITLE
Request to verify com.fluree group

### ISSUE THREAD

**Issue by cap10morgan** [clojars/administration#36]
I am requesting verification of an existing group. The group name is: com.fluree

- [ X ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ X ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/com.fluree has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
