### ISSUE TITLE
Verify com.lambdaisland for plexus

### ISSUE THREAD

**Issue by plexus** [clojars/administration#37]
I am requesting verification of a new group. The group name is: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
Thanks! 

The group https://clojars.org/groups/com.lambdaisland has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
