### ISSUE TITLE
Verify me.flowthing group

### ISSUE THREAD

**Issue by eerohele** [clojars/administration#38]
I am requesting verification of an existing group. The group name is: `me.flowthing`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/me.flowthing has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
