### ISSUE TITLE
New group verification: com.phronemophobic.membrane

### ISSUE THREAD

**Issue by phronmophobic** [clojars/administration#39]
I am requesting verification of a new group. The group name is: com.phronemophobic.membrane

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars phronmophobic`

I promise this is the last group I intend to create for the foreseeable future. I just have a bunch of related projects that I want to publish under the `com.phronemophobic.membrane` group as opposed to the more general `com.phronemophobic` group that I recently had verified.

Thank you!

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.phronemophobic.membrane has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

And no need to apologize! Feel free to create as many groups as you like - I'm happy to verify them all.

**Comment by phronmophobic** [comment]
Thank you!
