### ISSUE TITLE
Remove/block org.clojure artifacts

### ISSUE THREAD

**Issue by puredanger** [clojars/administration#4]
There are some old versions of Clojure that were uploaded to Clojars in the deep past. https://clojars.org/org.clojure/clojure

These artifacts all exist on Maven Central and those are the canonical *signed* artifacts someone should be downloading, not the ones from Clojars. Ideally, I think these should be removed, but it's hard for me to argue that that's urgent given they've been out there for years and I'm not really sure how many caches that would break.

But perhaps more importantly, I think that no one should be allowed to upload any new artifacts in the org.clojure group. I don't know if that means the core team needs to "claim" something or if this is a special case, so tell me what is best.

**Comment by tobias** [comment]
Hi @puredanger - I went ahead and deleted the `org.clojure` group completely (including all jars), and no one will be able to recreate it without DNS verification, so we should be good.
