### ISSUE TITLE
Verification request for com.ninjakoala

### ISSUE THREAD

**Issue by neilprosser** [clojars/administration#40]
I am requesting verification of an existing group. The group name is: `com.ninjakoala`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars neilprosser`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.ninjakoala has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
