### ISSUE TITLE
Verify fi.metosin & com.metosin

### ISSUE THREAD

**Issue by Deraen** [clojars/administration#41]
I am requesting verification of a new group. The group name is: 

- fi.metosin
- com.metosin

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

I've added the TXT records under `clojars` subdomains.

```
❯ dig +short TXT clojars.metosin.com
"clojars deraen"
```

**Comment by tobias** [comment]
The groups https://clojars.org/groups/com.metosin and https://clojars.org/groups/fi.metosin have been verified and you should now see the "verified" badge when you view them on Clojars. You can delete the TXT records if you like.

**Comment by Deraen** [comment]
Thanks!
