### ISSUE TITLE
Me admin

### ISSUE THREAD

**Issue by lastthyme** [clojars/administration#42]

**Comment by tobias** [comment]
Hi @lastthyme, can you provide more specifics about what you need?

**Comment by lastthyme** [comment]
Hello, Good Afternoon. My apologies in requesting to become admin over my Developments. Im looking to have this Repository published to do so, and if im incorrect about my direction please inform of how i could have “Icepick” obtained.

**Comment by tobias** [comment]
I'm sorry, I still don't understand. Are you asking to have a group verified or have some other issue with your account on https://clojars.org?

**Comment by jeffwidman** [comment]
I think this is a bot-generated account and they're using you to test/improve it. :-D

**Comment by tobias** [comment]
Yeah, mayhap. Closing.
