### ISSUE TITLE
Username change

### ISSUE THREAD

**Issue by haywoood** [clojars/administration#43]
Hello! I changed my GitHub handle a while back and I'm looking to update my Clojars username which is currently `Lsdafjklsd`.

🤦  so I actually created a new user with my desired username and added them as an admin to `com.github.haywoood`. So to simplify things if you could rename `lsdafjklsd` to just `haywood` that would be great.

**Comment by tobias** [comment]
Hi @haywoood:

I've updated your username: https://clojars.org/users/haywood

Can you confirm that you can log in using that username?

**Comment by haywoood** [comment]
Yes thank you so much!
