### ISSUE TITLE
com.cleancoders group creation

### ISSUE THREAD

**Issue by slagyr** [clojars/administration#45]
I am requesting verification of a new group. The group name is: com.cleancoders

- [ X ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ X ] I have added a TXT DNS record for the domain that has a value of `clojars slagyr`

**Comment by slagyr** [comment]
May I also have com.cleancoders.c3kit added as a verified group name?

**Comment by tobias** [comment]
The groups https://clojars.org/groups/com.cleancoders and https://clojars.org/groups/com.cleancoders.c3kit have been verified and you should now see the "verified" badge when you view them on Clojars. You can delete the TXT record if you like.

**Comment by slagyr** [comment]
Thanks!
