### ISSUE TITLE
Please verify the existing group net.ofnir via DNS entry

### ISSUE THREAD

**Issue by christoph-frick** [clojars/administration#46]
I am requesting verification of a existing group. The group name is: `net.ofnir`

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars ofnir-net`

Thanks for providing this free service to the Clojure community!

**Comment by tobias** [comment]
The group https://clojars.org/groups/net.ofnir has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
