### ISSUE TITLE
Please create group `org.kipz`

### ISSUE THREAD

**Issue by kipz** [clojars/administration#47]
I am requesting verification of a new group. The group name is: org.kipz

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.kipz has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
