### ISSUE TITLE
verify new group com.quantisan

### ISSUE THREAD

**Issue by Quantisan** [clojars/administration#49]
I am requesting verification of a new group. The group name is: com.quantisan

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars quantisan`

I added the TXT record to clojars.quantisan.com

```
$ dig +short TXT clojars.quantisan.com
"clojars quantisan"
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.quantisan has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
