### ISSUE TITLE
New group verification: jp.xcoo, com.xcoo and com.chrovis

### ISSUE THREAD

**Issue by notake** [clojars/administration#5]
I am requesting verification of a new group. The group name is: `jp.xcoo`, `com.xcoo` and `com.chrovis`.

**Comment by tobias** [comment]
Hi @notake!

Can you add TXT DNS records to the `xcoo.jp`, `xcoo.com`, and `chrovis.com` domains that contain `clojars-5 <your clojars username>` to prove ownership?

**Comment by notake** [comment]
Thank you @tobias !
Added TXT records to these domains. The username for Clojars is [`xcoo`](https://clojars.org/users/xcoo) .

**Comment by tobias** [comment]
Thanks! 

The groups `jp.xcoo`, `com.xcoo`, and `com.chrovis` have been verified. There isn't (yet) a way to see that on the site, but I hope to add that soon. You can delete the TXT records if you like.
