### ISSUE TITLE
org.rssys.* verification

### ISSUE THREAD

**Issue by mikeananev** [clojars/administration#50]
Hello!

I am requesting verification of a [new ] group. The group name is: org.rssys.*

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars mike1452`

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.rssys has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
