### ISSUE TITLE
org.rssys.apptemplate verification

### ISSUE THREAD

**Issue by mikeananev** [clojars/administration#51]
I am requesting verification of a new group. The group name is org.rssys.apptemplate: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars mike1452`

**Comment by tobias** [comment]
The group ohttps://clojars.org/groups/org.rssys.apptemplate has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
