### ISSUE TITLE
(io|com).github.cljsjs

### ISSUE THREAD

**Issue by Deraen** [clojars/administration#53]
I am requesting verification of a [new | existing] group. The group name is: io.github.cljsjs & com.github.cljsjs

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

I've created empty repo under the cljsjs github org: https://github.com/cljsjs/clojars_deraen

**Comment by tobias** [comment]
The groups https://clojars.org/groups/com.github.cljsjs and https://clojars.org/groups/io.github.cljsjs have been verified and you should now see the "verified" badge when you view them on Clojars. You can delete the verification repo if you like.
