### ISSUE TITLE
org.pinkgorilla verification

### ISSUE THREAD

**Issue by awb99** [clojars/administration#54]
I am requesting verification of a  existing group. The group name is: org.pinkgorilla

- [ ] This group is a [reverse-domain-based group]
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars pinkgorillawb`

**Comment by tobias** [comment]
Hi @awb99! Let me know when the TXT record is active.

**Comment by awb99** [comment]
dig +short TXT clojars.pinkgorilla.org
"pinkgorillawb"

**Comment by awb99** [comment]
it is ready

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.pinkgorilla has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
