### ISSUE TITLE
co.elastic Verification

### ISSUE THREAD

**Issue by haywoood** [clojars/administration#55]
I am requesting verification of a new group. The group name is: `co.elastic`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars elastic`

**Comment by tobias** [comment]
The group https://clojars.org/groups/co.elastic has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by haywoood** [comment]
Thanks @tobias!
