### ISSUE TITLE
com.teknql Verification Request

### ISSUE THREAD

**Issue by rschmukler** [clojars/administration#56]
I am requesting verification of a new group. The group name is: `com.teknql`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars rschmukler`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.teknql has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by rschmukler** [comment]
Thank you!
