### ISSUE TITLE
io.gamayun verification request

### ISSUE THREAD

**Issue by jvia** [clojars/administration#57]
I am requesting verification of a [new | existing] group. The group name is: 

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.gamayun has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
