### ISSUE TITLE
group-id verification request for the 404.taipei domain

### ISSUE THREAD

**Issue by green-coder** [clojars/administration#58]
I am requesting verification of a new group. The group name is:  taipei.404

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars green-coder`

**Comment by tobias** [comment]
The group https://clojars.org/groups/taipei.404 has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
