### ISSUE TITLE
Verification of three existing groups

### ISSUE THREAD

**Issue by jcf** [clojars/administration#6]
I am requesting verification of existing groups. The group names are:

- `invetica`
- `jcf`

I’d like to verify `oauth` too, but I don’t have the Org on GitHub, so expect that won’t be possible?

**Comment by tobias** [comment]
Hi @jcf!

We won't be able to verify any of those groups, unfortunately. We are only verifying reverse-domain-based groups (see https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq). 

But these changes don't impact existing libraries - you will be able to continue to release new versions of them without issue. You'll only need verified groups for **new** libraries.

**Comment by tobias** [comment]
I'm closing this issue, but feel free to re-open if you would like to discuss further.
