### ISSUE TITLE
Verification request: com.kardans

### ISSUE THREAD

**Issue by kardan** [clojars/administration#60]
I am requesting verification of a [new | existing] group. The group name is: com.kardans

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.kardans has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by kardan** [comment]
Thanks!
