### ISSUE TITLE
place.cork group creation

### ISSUE THREAD

**Issue by ZehCnaS34** [clojars/administration#62]
I am requesting verification of a new group. The group name is: place.cork

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/place.cork has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
