### ISSUE TITLE
New group creation: com.exoscale

### ISSUE THREAD

**Issue by pyr** [clojars/administration#65]
I am requesting verification of a new group. The group name is: `com.exoscale`

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by pyr** [comment]
Last one I promise!

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.exoscale has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

And feel free to verify as many groups as you like :)
