### ISSUE TITLE
com.joshuadavey

### ISSUE THREAD

**Issue by jgdavey** [clojars/administration#66]
I am requesting verification of existing group. The group name is: com.joshuadavey

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars jgdavey`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.joshuadavey has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
