### ISSUE TITLE
Verification request for org.suskalo

### ISSUE THREAD

**Issue by IGJoshua** [clojars/administration#67]
I am requesting verification of an existing group. The group name is: org.suskalo

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars suskeyhose`

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.suskalo has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
