### ISSUE TITLE
New Group Creation + Verification: `io.trosa`

### ISSUE THREAD

**Issue by iomonad** [clojars/administration#68]
I am requesting verification of a new group. The group name is: `io.trosa`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars iomonad`

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.trosa has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by iomonad** [comment]
thanks
