### ISSUE TITLE
New Group Creation + Verification: fr.mcorbin

### ISSUE THREAD

**Issue by mcorbin** [clojars/administration#69]
I am requesting verification of a new group. The group name is: fr.mcorbin

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars mcorbin`

**Comment by tobias** [comment]
The group https://clojars.org/groups/fr.mcorbin has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by mcorbin** [comment]
Thank you.
