### ISSUE TITLE
clj-commons

### ISSUE THREAD

**Issue by slipset** [clojars/administration#7]
I am requesting verification of a  existing group. The group name is: clj-commons

**Comment by tobias** [comment]
Hi @slipset!

We won't be able to verify clj-comons, unfortunately. We are only verifying reverse-domain-based groups (see https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq). 

But these changes don't impact existing libraries - you will be able to continue to release new versions of them without issue. You'll only need verified groups for **new** libraries, so you may need to switch to `org.clj-commons` for new libraries.

**Comment by tobias** [comment]
I'm closing this issue, but feel free to re-open if you would like to discuss further.
