### ISSUE TITLE
org.scicloj group verification

### ISSUE THREAD

**Issue by genmeblog** [clojars/administration#70]
I am requesting verification of a new group. The group name is: org.scicloj

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars generateme`

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.scicloj has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
