### ISSUE TITLE
Requesting org.radare domain verification for user: mgdan

### ISSUE THREAD

**Issue by trufae** [clojars/administration#71]
I am requesting verification of a [new | existing] group. The group name is: *org.radare*

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars mgdan`

**Comment by tobias** [comment]
Hi @trufae!

Your TXT record is `clojars mdgan`, not `clojars mgdan`. Would you mind correcting that?

**Comment by trufae** [comment]
Ouch! Damn race conditions! it should be good now

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.radare has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
