### ISSUE TITLE
org.domaindrivenarchitecture

### ISSUE THREAD

**Issue by jerger** [clojars/administration#72]
I am requesting verification of a [new | existing] group. The group name is: 

org.domaindrivenarchitecture

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
Hi @jerger! I'm not seeing a `TXT` record for `domaindrivenarchitecture.org` that matches the `clojars <username>` format. Can you add that and let me know when it is ready?

**Comment by jerger** [comment]
You're right missed one of the save buttons ... now it is :-)

dig @ns3.routing.net domaindrivenarchitecture.org txt

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.domaindrivenarchitecture has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
