### ISSUE TITLE
Group Verification global.stash

### ISSUE THREAD

**Issue by cbevans** [clojars/administration#73]
I am requesting verification of a [new] group. The group name is: global.stash

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

Please check TXT for clojars.stash.global - we have an existing TXT entry for stash.global and we're not sure what will break if we modify that! We're requesting global.stash for the group name tho. Thank you!

**Comment by tobias** [comment]
The group https://clojars.org/groups/global.stash has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like. The script I use for this only adds one user as a member, so I added `stash`. You'll need to log in as `stash` and add `stash-chris` as a member if you want that account be be able to deploy.
