### ISSUE TITLE
Verify new com.amperity group

### ISSUE THREAD

**Issue by greglook** [clojars/administration#74]
I am requesting verification of a new group. The group name is: `com.amperity`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars greglook`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.amperity has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
