### ISSUE TITLE
verification of a group

### ISSUE THREAD

**Issue by reborg** [clojars/administration#75]
Hello,

I am requesting verification for an already existing group. The group name is: `tech.droit`

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq), see http://droit.tech
- [X] I have added a TXT DNS record for the domain that has a value of `clojars reborg`, see `dig -t txt droit.tech`

Thanks.

**Comment by tobias** [comment]
The group https://clojars.org/groups/tech.droit has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
