### ISSUE TITLE
com.cgore reverse domain based group verification

### ISSUE THREAD

**Issue by cgore** [clojars/administration#76]
I am requesting verification of a [new | existing] group. The group name is: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

```
5/25/2021 Tue 11:48:34 AM ~/programming/clojure/web3clj $ dig -t txt cgore.com

; <<>> DiG 9.16.6-Ubuntu <<>> -t txt cgore.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27551
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;cgore.com.			IN	TXT

;; ANSWER SECTION:
cgore.com.		3006	IN	TXT	"foo=bar"
cgore.com.		3006	IN	TXT	"clojars cgore"

;; Query time: 3 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue May 25 11:49:42 CDT 2021
;; MSG SIZE  rcvd: 84

```

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.cgore has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
