### ISSUE TITLE
New Group Creation: io.fkcss

### ISSUE THREAD

**Issue by raystubbs** [clojars/administration#77]
I am requesting verification of a new group. The group name is: io.fkcss

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.fkcss has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by raystubbs** [comment]
Sweet, thanks!
