### ISSUE TITLE
Verify group link.szabo.mauricio

### ISSUE THREAD

**Issue by mauricioszabo** [clojars/administration#78]
I am requesting verification of a new group. The group name is: `link.szabo.mauricio`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars mauricioszabo`

**Comment by tobias** [comment]
The group https://clojars.org/groups/link.szabo.mauricio has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
