### ISSUE TITLE
Request to verify com.7theta

### ISSUE THREAD

**Issue by sandhu** [clojars/administration#8]
I am requesting verification of an existing group. The group name is: com.7theta

We already have several libraries published under this group name https://clojars.org/groups/com.7theta

The corresponding Github group is https://github.com/7theta

**Comment by tobias** [comment]
Hi @sandhu!

Can you add a TXT DNS record for 7theta.com that contains `clojars-8 sandhu` to confirm ownership of the domain?

**Comment by sandhu** [comment]
Added with a TTL of 24H.

**Comment by tobias** [comment]
Thanks! 

The group `com.7theta` has been verified. There isn't (yet) a way to see that on the site, but I hope to add that soon. You can delete the TXT record if you like.

**Comment by sandhu** [comment]
Thank you.
