### ISSUE TITLE
Existing Group Verification - org.graphqlize

### ISSUE THREAD

**Issue by tamizhvendan** [clojars/administration#81]
I am requesting verification of an existing group. The group name is: `org.graphqlize`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars tamizhvendan`

**Comment by tamizhvendan** [comment]
```
➜  dig -t txt graphqlize.org

; <<>> DiG 9.10.6 <<>> -t txt graphqlize.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43412
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;graphqlize.org.			IN	TXT

;; ANSWER SECTION:
graphqlize.org.		600	IN	TXT	"clojars tamizhvendan"

;; Query time: 37 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Jun 03 09:31:57 IST 2021
;; MSG SIZE  rcvd: 76
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/org.graphqlize has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
