### ISSUE TITLE
New Group Creation - com.kalvify

### ISSUE THREAD

**Issue by tamizhvendan** [clojars/administration#82]
I am requesting verification of a new group. The group name is: `com.kalvify`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars tamizhvendan`

**Comment by tamizhvendan** [comment]
```
➜  dig -t txt kalvify.com

; <<>> DiG 9.10.6 <<>> -t txt kalvify.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55640
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;kalvify.com.			IN	TXT

;; ANSWER SECTION:
kalvify.com.		600	IN	TXT	"clojars tamizhvendan"
kalvify.com.		600	IN	TXT	"v=spf1 include:_spf.google.com ~all"

;; Query time: 467 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Jun 03 10:15:16 IST 2021
;; MSG SIZE  rcvd: 121
```

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.kalvify has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
