### ISSUE TITLE
Verification request for pisano group

### ISSUE THREAD

**Issue by tugh** [clojars/administration#83]
I am requesting verification of a new group. The group name is: `co.pisano`

I also want to verify `pisano` group but as far as I understand no user is allowed to verify such groups. If this is not true can you please give me the steps to verify `pisano` group? 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars tugh`

**Comment by tobias** [comment]
The group https://clojars.org/groups/co.pisano has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

As for `pisano` - we aren't verifying non-reverse-domain-based groups. Existing projects in that group can have new versions deployed, but new projects will need to be deployed to a verified group.
