### ISSUE TITLE
Verify dominic.io

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojars/administration#85]
I am requesting verification of a existing group. The group name is: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.dominic has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
