### ISSUE TITLE
Verifying `io.helins` group

### ISSUE THREAD

**Issue by helins** [clojars/administration#86]
I am requesting verification of an **existing** group. The group name is: **io.helins** (account is helins)

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars helins`

**Comment by tobias** [comment]
The group https://clojars.org/groups/io.helins has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
