### ISSUE TITLE
io.homebase

### ISSUE THREAD

**Issue by smothers** [clojars/administration#88]
I am requesting verification of a new group. The group name is: 

io.homebase

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
Hi Chris!

The group https://clojars.org/groups/io.homebase has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by smothers** [comment]
Hey Toby! Thanks for the speedy turnaround.
