### ISSUE TITLE
Request to verify com.danboykis

### ISSUE THREAD

**Issue by danboykis** [clojars/administration#9]
I am requesting verification of a existing group. The group name is: com.danboykis

**Comment by tobias** [comment]
Hi @danboykis!

Can you add a TXT DNS record for danboykis.com that contains `clojars-9 <your clojars username>` to confirm ownership of the domain?

**Comment by danboykis** [comment]
Done

`dig +short @ns1.linode.com clojars-9.danboykis.com TXT`

**Comment by tobias** [comment]
Thanks! 

The group `com.danboykis` has been verified. There isn't (yet) a way to see that on the site, but I hope to add that soon. You can delete the TXT record if you like.
