### ISSUE TITLE
New group: com.6pages

### ISSUE THREAD

**Issue by adamtait** [clojars/administration#90]
I am requesting verification of a new group. The group name is: `com.6pages`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars adamtait` (note: it's one record in a grouped TXT record on the root domain)

**Comment by adamtait** [comment]
Thanks in advance, Clojars team! You guys are awesome! 🏆

**Comment by tobias** [comment]
Thanks for the kind words!

The group https://clojars.org/groups/com.6pages has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
