### ISSUE TITLE
Existing Group Verification - com.teamgantt

### ISSUE THREAD

**Issue by brianium** [clojars/administration#91]
I am requesting verification of an existing group. The group name is: com.teamgantt

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars brianium`

**Comment by tobias** [comment]
Hi @brianium! I'm not seeing the Clojars TXT record for teamgantt.com, just the spf one:

```
$ dig txt +short teamgantt.com
"v=spf1 include:_spf.google.com include:sendgrid.net include:sparkpostmail.com include:helpscoutemail.com include:spf.braintreegateway.com mx:teamgantt.com -all"
```

Can you let me know when that is up?

**Comment by brianium** [comment]
@tobias so sorry, I made a mistake. Can you try again please?

**Comment by brianium** [comment]
and of course thank you 🙇🏻

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.teamgantt has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

My pleasure!
