### ISSUE TITLE
Existing group verification for: io.logicblocks

### ISSUE THREAD

**Issue by tobyclemson** [clojars/administration#92]
I am requesting verification of an existing group. The group name is: io.logicblocks

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars tobyclemson`

**Comment by tobias** [comment]
Hello fellow Tobias/Toby :) 

The group https://clojars.org/groups/io.logicblocks has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by tobyclemson** [comment]
Hi Tobias,

Wow, thanks for the speedy verification, wasn't expecting it to get resolved on a Saturday.

Thanks again,
Toby (Tobias when I've done something wrong)
