### ISSUE TITLE
Verification of com.cnuernber - chrisn Clojars username

### ISSUE THREAD

**Issue by cnuernber** [clojars/administration#93]
I am requesting verification of a new group. The group name is: 

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for cnuernber.com that has a value of `clojars chrisn`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.cnuernber has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by cnuernber** [comment]
Got it, thanks!
