### ISSUE TITLE
Group Verification for com.yetanalytics

### ISSUE THREAD

**Issue by milt** [clojars/administration#94]
I am requesting verification of a existing group. The group name is: com.yetanalytics

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars milt`

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.yetanalytics has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
