### ISSUE TITLE
New group request for `com.ponderware`

### ISSUE THREAD

**Issue by ponderware** [clojars/administration#95]
I am requesting verification of a new group. The group name is: `com.ponderware`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record to the domain `ponderware.com` that has a value of `clojars ponderware`

Thank You.

**Comment by tobias** [comment]
The group https://clojars.org/groups/com.ponderware has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by ponderware** [comment]
Thank you. Really appreciate the clojars project, you folks are an amazing asset to clojure ecosystem
