### ISSUE TITLE
Group verification xyz.thoren

### ISSUE THREAD

**Issue by johanthoren** [clojars/administration#98]
I am requesting verification of a [new] group. The group name is: xyz.thoren

- [X] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [X] I have added a TXT DNS record for the domain that has a value of `clojars johanthoren`

**Comment by tobias** [comment]
The group https://clojars.org/groups/xyz.thoren has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.
