### ISSUE TITLE
Request `dev.jarohen` group-id

### ISSUE THREAD

**Issue by jarohen** [clojars/administration#99]
I am requesting verification of a new group. The group name is: `dev.jarohen`

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added a TXT DNS record for the domain that has a value of `clojars james-henderson`

Cheers!

**Comment by tobias** [comment]
The group https://clojars.org/groups/dev.jarohen has been verified and you should now see the "verified" badge when you view it on Clojars. You can delete the TXT record if you like.

**Comment by jarohen** [comment]
Great, thanks! :pray:
